### ISSUE TITLE
[feature] Add cri-o pre-built binaries tar

### ISSUE THREAD

**Issue by kairen** [kubernetes-sigs/cri-o#1141]
Hi all, Is there any pre-built binary files for the release? like as [cri-containerd](https://github.com/kubernetes-incubator/cri-containerd/releases/download/v1.0.0-alpha.1/cri-containerd-1.0.0-alpha.1.tar.gz) release.

**Comment by runcom** [comment]
Not yet, we're working on that but we have Rpms and debs for fedora/ubuntu/centos so best for now would be to install from your package manager

**Comment by kairen** [comment]
@runcom Okay, thanks you for your help!

**Comment by runcom** [comment]
also, consider a tarball with CRI-O isn't something you really want as crio is a dynamic binary and it's really unlikely that works on every os. We might need to some help on this :confused:

**Comment by kairen** [comment]
@runcom  Yes, I can try to help this request!

**Comment by kfox1111** [comment]
Where are the rpms? best I could find is https://cbs.centos.org/repos/virt7-container-common-candidate/x86_64/os/Packages/

**Comment by rhatdan** [comment]
@lsm5 Can you update this ISSUE with locations for rpms for Centos and then close.

**Comment by Bregor** [comment]
Every release contains the phrase "Please try out the release binaries and report any issues", but no binaries are linked :(

**Comment by rhatdan** [comment]
No action for quite a while.  If community wants static binaries then we will accept PRs.  Until then I will close this.  Reopen if you disagree.

**Comment by kfox1111** [comment]
Just a datapoint. I've been using containerd more of late, as they provide exactly this while cri-o doesnt. Better yet would be centos rpms, but neither runtime provides those.

**Comment by amimof** [comment]
Not sure why this issue closed but i would gladly help out. I would personally LOVE to see pre-built binaries under "releases".

**Comment by lsm5** [comment]
> Just a datapoint. I've been using containerd more of late, as they provide exactly this while cri-o doesnt. Better yet would be centos rpms, but neither runtime provides those.

Hmm, centos PaaS SIG does provide those: https://cbs.centos.org/koji/packageinfo?packageID=5695

Also: https://cbs.centos.org/repos/paas7-crio-113-candidate/x86_64/os/Packages/ and
https://cbs.centos.org/repos/paas7-crio-112-candidate/x86_64/os/Packages/

I have a TODO to create 1.14 repos.

**Comment by lsm5** [comment]
I don't think centos base would have those rpms though, since those are not shipped in RHEL to begin with.

**Comment by kfox1111** [comment]
Does https://cbs.centos.org/koji/packageinfo?packageID=5695 feed into a repo?

I'm kind of reluctant to use packages out of any repo with 'candidate' in its title.

**Comment by lsm5** [comment]
On Tue, Apr 09, 2019 at 08:42:01AM -0700, kfox1111 wrote:
> Does https://cbs.centos.org/koji/packageinfo?packageID=5695 feed into a repo?
> 
> I'm kind of reluctant to use packages out of any repo with 'candidate' in its title.

I'll have those flow into -testing and -release and get them synced on
buildlogs.c.o


-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5
