### ISSUE TITLE
Consider supporting Service Fabric as a client

### ISSUE THREAD

**Issue by AceHack** [kubernetes-sigs/cri-o#1238]
Please consider Service Fabric as a second first-class client for CRI-O.

See related issue on service fabric
https://github.com/Azure/service-fabric-issues/issues/729

**Comment by rhatdan** [comment]
I guess this has never gone anywhere?

**Comment by rhatdan** [comment]
No action in another year.  I guess this is not something we need..  Reopen if you disagree.
