### ISSUE TITLE
Failed to mount container: Can't stat lower layer

### ISSUE THREAD

**Issue by mikkeloscar** [kubernetes-sigs/cri-o#1241]
**Description**

I originally posted this as a support request in **#sig-node** but was asked to open an issue here as it may be a bug.

I'm trying to run cri-o on my Arch Linux based cluster and I'm having problems getting containers to run. When I run crio with `--log-level debug` I see the following errors when kubelet is trying to create containers:

```
DEBU[2017-12-29 23:13:35.664572746+01:00] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage]docker.io/kubernetes/pause:latest" 
DEBU[2017-12-29 23:13:35.688453811+01:00] created pod sandbox "ccd895509440f38d515735b9e60bc14aef92c22ea200ddaeb4f629c848553e82" 
DEBU[2017-12-29 23:13:35.693721290+01:00] pod sandbox "ccd895509440f38d515735b9e60bc14aef92c22ea200ddaeb4f629c848553e82" has work directory "/var/lib/containers/storage/overlay-containers/ccd895509440f38d515735b9e60bc14aef92c22ea200ddaeb4f629c848553e82/userdata" 
DEBU[2017-12-29 23:13:35.693854294+01:00] pod sandbox "ccd895509440f38d515735b9e60bc14aef92c22ea200ddaeb4f629c848553e82" has run directory "/var/run/containers/storage/overlay-containers/ccd895509440f38d515735b9e60bc14aef92c22ea200ddaeb4f629c848553e82/userdata" 
DEBU[2017-12-29 23:13:35.699290618+01:00] failed to mount container "ccd895509440f38d515735b9e60bc14aef92c22ea200ddaeb4f629c848553e82": Can't stat lower layer "/var/lib/containers/storage/overlay/l/KNN2MJ2JT5X2QEBVZDUAX2JABK": stat /var/lib/containers/storage/overlay/l/KNN2MJ2JT5X2QEBVZDUAX2JABK: no such file or directory
```
`/var/lib/containers/storage/overlay/l` exists, but I don't see the `KNN2MJ2JT5X2QEBVZDUAX2JABK` folder/file or anything else being created inside.

I'm running crio like this:

```
sudo crio --log-level debug
```

with the default `crio.conf` and see this error all the time when kubelet is trying to recreate containers.

**Describe the results you received:**

Debug log showing container failed to run with an error message about a missing folder/file.

**Describe the results you expected:**

Expected the container to be created and run, or maybe a more insightful error message with information about why the specific file/folder wasn't created.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.9.0
commit: "2d067eaa2d7c9a2fe66b3105bd82fd19c2944d9b-dirty"
```

It was built from this custom Arch Linux PKGBUILD: https://github.com/mikkeloscar/packages/blob/master/cri-o/PKGBUILD

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Scaleway bare metal server with custom Arch Linux installation.

**Comment by runcom** [comment]
Could you provide kernel version and double check that the kernel has the overlay CONFIG enabled

**Comment by mikkeloscar** [comment]
Good point, I'm using the kernel provided by scaleway, not the default Arch Linux kernel. It does look correct though:

```
$ uname -r
4.14.5-mainline-rev1

$ zcat /proc/config.gz | grep OVERLAY
# CONFIG_OF_OVERLAY is not set
CONFIG_OVERLAY_FS=m
# CONFIG_OVERLAY_FS_REDIRECT_DIR is not set
# CONFIG_OVERLAY_FS_INDEX is not set

$ lsmod | grep overlay
overlay                57344  1
```

**Comment by rhatdan** [comment]
@nalind @rhvgoyal PTAL

**Comment by rhatdan** [comment]
@mikkeloscar Is this still an issue?  Or can I close this?

**Comment by mikkeloscar** [comment]
@rhatdan the latest version I tried (v1.9.9) still had this issue.

**Comment by rhatdan** [comment]
I believe this is now fixed in latest CRI-O, Reopen if you disagree.
