### ISSUE TITLE
Can't access tty on running or new pods

### ISSUE THREAD

**Issue by linets-soporte** [kubernetes-sigs/cri-o#1246]
**Description**

Can't connect to tty inside pods after replacing docker with cri-o on a working k8s cluster.

**Steps to reproduce the issue:**
1. Install a k8s using something. I'm case kubespray+ubuntu 16.04.
2. Use the cluster!
3. Replace docker with cri-o.
4. Watch everything work!
5. Try to attach your console to a pod with something like this: kubectl exec -ti nginx-7c87f569d-dmtj7 -- /bin/bash 

**Describe the results you received:**

Only on cri-o nodes:

laptop-4:~ smorales$ kubectl exec -ti nginx-7c87f569d-dmtj7 -- /bin/bash
error: Timeout occured

**Describe the results you expected:**

The tty =).

**Additional information you deem important (e.g. issue happens only occasionally):**

With "kubectl run" it's the same but with more info:

```
kubectl run tmp-shell --overrides='{ "apiVersion": "extensions/v1beta1", "spec": { "nodeSelector": { "iscrio": "true" } } }' --rm -i --tty --image centos -- /bin/bash
If you don't see a command prompt, try pressing enter.
                                                      Error attaching, falling back to logs: Timeout occured
P
P
P [root@tmp-shell-6df66f55cd-d64hq /]#

```

In the kubelet of the nodes running crio I have this:
```
Jan 05 19:47:05 k8s-vpsguru-53wryy kubelet[9341]: I0105 19:47:05.083433    9341 server.go:779] POST /stats/container/: (75.584592ms) 200 [[Go-http-client/1.1] 192.168.1.12:35808]
Jan 05 19:47:07 k8s-vpsguru-53wryy kubelet[9341]: E0105 19:47:07.511853    9341 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 2; ignoring extra CPUs
Jan 05 19:47:07 k8s-vpsguru-53wryy kubelet[9341]: E0105 19:47:07.546862    9341 helpers.go:468] PercpuUsage had 0 cpus, but the actual number is 2; ignoring extra CPUs
Jan 05 19:47:07 k8s-vpsguru-53wryy kubelet[9341]: I0105 19:47:07.734502    9341 kubelet.go:1871] SyncLoop (PLEG): "tmp-shell-6df66f55cd-fjq26_default(3279d638-f251-11e7-b042-fa163eeabf84)", event: &pleg.PodLifecycleEvent{ID:"3279d638-f251-11e7-b042-fa163eeabf84", Type:"ContainerStarted", Data:"48347ea68820498e7e962cb5e2d03eb6cfbd31478d6b9464f27701b7a36e1990"}
Jan 05 19:47:07 k8s-vpsguru-53wryy kubelet[9341]: I0105 19:47:07.859180    9341 server.go:779] POST /attach/default/tmp-shell-6df66f55cd-fjq26/tmp-shell?input=1&output=1&tty=1: (2.141988ms) 302 [[kubectl/v1.9.1 (darwin/amd64) kubernetes/3a1c944] 192.168.1.4:51804]
```

**Output of `crio --version`:**

```
crio version 1.9.0
commit: ""
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* Ubuntu 16.04
* K8s versions:
   ```
  Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T19:59:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
   Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3+coreos.0", GitCommit:"f96beb2e925b0bb4e6ac0de746c7155dcd8fdc10", GitTreeState:"clean", BuildDate:"2017-11-13T10:18:37Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by runcom** [comment]
@mrunalp is this the issue you're fixing for which we need to enable the skipped test?

Thanks for the report! It should be a known bug!

**Comment by mrunalp** [comment]
@runcom No, this isn't related. 
This works fine for me locally. Looks like the streaming server port may not be open.

@linets-soporte Is port 10010 open? It is needed to connect to the streaming server used for exec/attach.

**Comment by linets-soporte** [comment]
@runcom, so the k8s node running the pod needs a Public IP and a Security Group that's allow ingress on port 10010? I ask this because, with docker, there's no problem and I only need the k8s masters with public ips (because of the apiserver).

**Comment by runcom** [comment]
> @runcom, so the k8s node running the pod needs a Public IP and a Security Group that's allow ingress on port 10010? I ask this because, with docker, there's no problem and I only need the k8s masters with public ips (because of the apiserver).

that's because the dockershim runs directly in the apiserver on the master, whether if you use something like cri-o or cri-containerd you get to do what you said :)

**Comment by linets-soporte** [comment]
@runcom Wow, can you help me understand somethings:

- I tried the command from the k8s master. Same problem.
- k8s master and nodes are in the same internal network (I'm using Openstack) and the port you mention is open, visible and responding between vms.
- A process running  in a node on an internal network (lika a vpc in AWS) only knows it's internal IP, so, Why my laptop would try to connect to the Public IP of the k8s node running the pod?
- Finally, as I mentioned before, when using "kubectl run -ti ..." I can see the PROMPT just before the error.


I ran "strace" when using "kubectl" but I only saw the "connect" and "read" to the api server.

Cheers.

P.D: I followed a guide and modified only the kubelet process to get cri-o working. Do I need something else on the API Server?

P.D: Kubespray, the tool I used, run all the k8s software on containers (except) with hyperkube

**Comment by mrunalp** [comment]
The `P` in the output may suggest that conmon and/or crio version aren't quite correct. @lsm5 can you double check that ubuntu ppa has the correct versions?

**Comment by mrunalp** [comment]
@linets-soporte Can you start a httpd pod, curl it and then try to read logs using kubectl logs? That will tell us if conmon/crio are out of sync for you.

**Comment by linets-soporte** [comment]
I can confirm that all pods running on the cri-o nodes print logs when executing "kubectl get pods". That include kube-system (flannel, etc) pods. Still no tty.

**Comment by linets-soporte** [comment]
Quick update.

I removed crio from Ubuntu and reinstalled the software using the tutorial.

Now I have this on kubelet "Manifest does not match provided manifest digest sha256:bf96292eedc661a17bdf183b28c004e8e423b2f4a52c752ced1f000b945ae123".

I already deleted all containers with crictl.

I will try one more time before reinstalling all thing an closing this.

Any tip on the "Manifest does not match provided manifest digest sha256:bf96292eedc661a17bdf183b28c004e8e423b2f4a52c752ced1f000b945ae123" error?

**Comment by mrunalp** [comment]
@linets-soporte Can you remove all the images from the local store and retry?

**Comment by linets-soporte** [comment]
@mrunalp you were rigth!

But I have the same problem: No tty or attach works on containers created with cri-o (k8s master to k8s master or k8s master to k8s node).

I triple check my security groups.

I followed this https://github.com/kubernetes-incubator/cri-o/blob/master/kubernetes.md to remove docker.

Do I need to read another doc? All the containers are running and this is the only issue so far.

I will try a clean installation of k8s. Any sugestions for a multimaster k8s cluster? Kubespray with atomic? or rhel 7 perhaps?

Cheers.

**Comment by mrunalp** [comment]
@linets-soporte Are you using the release-1.8 branch? Also, did you make sure that your conmon binary is also compiled and copied to the location specified in crio.conf? One more thing you could try is make sure that local-up-cluster works to rule out any compatibility issues between cri-o and conmon.

**Comment by rhatdan** [comment]
@linets-soporte Is this still an issue?  If I don't here from you in a week, I will close this figuring it is solved.

**Comment by umohnani8** [comment]
@linets-soporte if this is an issue please reopen, closing for now.
