### ISSUE TITLE
no such file or directory during container creation.

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-sigs/cri-o#1258]
**Description**

I can have a working pod in k8s, delete it and recreate it and with zero changes to the pod.yaml, it fails to launch.

**Describe the results you received:**
pod enters CreateContainerError

kubelet logs:
Jan 16 11:19:33 zathras.emsl.pnl.gov kubelet[1754]: E0116 11:19:33.930641    1754 pod_workers.go:186] Error syncing pod 277ece5d-faf2-11e7-b013-d481d7de48ad ("test4_default(277ece5d-faf2-11e7-b013-d481d7de48ad)"), skipping: failed to "StartContainer" for "main" with CreateContainerError: "container create failed: container_linux.go:274: starting container process caused \"process_linux.go:366: container init caused \\\"rootfs_linux.go:57: mounting \\\\\\\"/var/lib/kubelet/pods/277ece5d-faf2-11e7-b013-d481d7de48ad/etc-hosts\\\\\\\" to rootfs \\\\\\\"/var/lib/containers/storage/overlay/ea92f6ebb1abf41dd2b3583fc1dc85340c7ecb4fd4098e10790986d72edab9ee/merged\\\\\\\" at \\\\\\\"/var/lib/containers/storage/overlay/ea92f6ebb1abf41dd2b3583fc1dc85340c7ecb4fd4098e10790986d72edab9ee/merged/etc/hosts\\\\\\\" caused \\\\\\\"no such file or directory\\\\\\\"\\\"\"\n"
^C

**Describe the results you expected:**
a working container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
crio version 1.9.0
k8s 1.9.0

obtained from:
https://cbs.centos.org/repos/virt7-container-common-candidate/x86_64/os/Packages/

**Additional environment details (AWS, VirtualBox, physical, etc.):**
this is on a bare metal laptop.

**Comment by mrunalp** [comment]
What version of centos are you on? Also can you share your crio.conf?
cc: @nalind

**Comment by kfox1111** [comment]
centos 7.4

the config without any comments:
 sed '/^#/d; /^$/d' /etc/crio/crio.conf 
[crio]
root = "/var/lib/containers/storage"
runroot = "/var/run/containers/storage"
storage_driver = "overlay"
storage_option = [
	"overlay.override_kernel_check=1",
]
[crio.api]
listen = "/var/run/crio/crio.sock"
stream_address = ""
stream_port = "10010"
file_locking = true
[crio.runtime]
runtime = "/usr/bin/runc"
default_workload_trust = "trusted"
no_pivot = false
conmon = "/usr/libexec/crio/conmon"
conmon_env = [
	"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
]
selinux = true
seccomp_profile = "/etc/crio/seccomp.json"
apparmor_profile = "crio-default"
cgroup_manager = "cgroupfs"
hooks_dir_path = "/usr/share/containers/oci/hooks.d"
default_mounts = [
	"/usr/share/rhel/secrets:/run/secrets", 
]
pids_limit = 1024
enable_shared_pid_namespace = false
log_size_max = -1
[crio.image]
default_transport = "docker://"
pause_image = "kubernetes/pause"
pause_command = "/pause"
signature_policy = ""
image_volumes = "mkdir"
insecure_registries = [
]
registries = [
]
[crio.network]
network_dir = "/etc/cni/net.d/"
plugin_dir = "/usr/libexec/cni"

**Comment by mrunalp** [comment]
Can you get logs from crio in debug mode (--log-level debug) as well?

**Comment by ashcrow** [comment]
Only thing missing from the default config looks to be from ``crio.runtime``: ``runtime_untrusted_workload = ""`` though it should not be related since it's optional.

**Comment by kfox1111** [comment]
yeah. I had clear containers setup. but disabled it to debug just to be sure it wasn't cc.

Another datapoint. I can only reproduce it it seems with pods that have hostNetwork: true. if I comment it out, the pod launches successfully.

Oddly, the k8s itself has several pods including etcd launched hostNetwork: true running to even service that way. I'm guessing if I went to relaunch one of them now, it would fail.

So seems like it may be a race or bug related to hostNetwork.

**Comment by mrunalp** [comment]
@kfox1111 Can you share your pod yaml file so we can try to reproduce the issue?

**Comment by runcom** [comment]
I cannot reproduce this issue on F27 with latest CRI-O. `etc-hosts` from kube should be also completely ignored since we're running hostNetwork: true.
Here's my yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  hostNetwork: true
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
```
I can create, delete and re-create it just fine.

**Comment by kfox1111** [comment]
I used the following, but even the kubeadm manifests in /etc/kubernetes/manifests show the issue:
apiVersion: v1
kind: Pod
metadata:
  name: kfox-test
spec:
   hostNetwork: true
 containers:
  - name: main
    command:
    - /bin/sh
    - -c
    - |
      while true; do sleep 1000; done
    image: docker.io/library/busybox
    imagePullPolicy: IfNotPresent

**Comment by kfox1111** [comment]
I've tried the centos rpms and saw it frequently.

I built:
(venv)[root@zathras ~]# crio --version
crio version 1.9.1-dev
commit: "5321ae20e4428093cdadb80f550e872f75006c32"

and it went away for a little while and then started coming back. (though during that time I was doing less net=host related changes)

Please try with centos 7.

**Comment by runcom** [comment]
I'll try it, it's super weird though, etc-hosts in kube is already created and present at the time CRI-O is asked to mount it in the container. Can't see how this could be a race. I'll try and repro on CentOS

**Comment by rhatdan** [comment]
@kfox1111 @runcom Is this still an issue?

**Comment by kfox1111** [comment]
unsure. I stopped using cri-o for a little while when my laptop ate itself. Will try again soon.

**Comment by rhatdan** [comment]
@kfox1111 Good we want you back.  :^)

**Comment by umohnani8** [comment]
@kfox1111 checking in again, is it still an issue?

**Comment by kfox1111** [comment]
Too long ago to tell. I'm going to just close this for now.

Thanks,
Kevin
