### ISSUE TITLE
1.9.0-1~ubuntu16.04.2~ppa1 missing from ubuntu repository

### ISSUE THREAD

**Issue by mrIncompetent** [kubernetes-sigs/cri-o#1294]
I saw that the cri-o package `1.9.0-1~ubuntu16.04.2~ppa1` from the Ubuntu apt repository was deleted.
Instead there's now `1.9.1-1~ubuntu16.04.2~ppa1`

Was there a particular reason behind this?
Cant both packages exist?

**Comment by mrIncompetent** [comment]
It happened again with `1.9.2-1~ubuntu16.04.2~ppa1` :disappointed: 
Is there any reason for this?

As cri-o's versioning is bound the the kubernetes minor version, it will be required to pin the package version of cri-o as soon as cri-o 1.10 will be released.
Or will cri-o 1.10 be backwards-compatible?

**Comment by lsm5** [comment]
aargh, reason for this is that I forgot to look at setting up hosting multiple builds simultaneously. my bad entirely.

Btw, maintaining multiple simultaneous builds might sooner or later end up being a pain in my @$$, so I'll welcome co-maintainers if anyone's interested :)

**Comment by lsm5** [comment]
so it seems the gopher team maintains separate versions together by including the version number in the package name itself, @runcom how many versions are we looking to support right now?

**Comment by lsm5** [comment]
@mrIncompetent I just submitted `cri-o-1.9.3` to PPA. Note that version string is appended to the package name itself, while `cri-o` right now is 1.9.2. Let me know what versions you're looking to deploy simultaneously and I'll see what I can do.

See: https://launchpad.net/~projectatomic/+archive/ubuntu/ppa/+packages

**Comment by mrIncompetent** [comment]
Hey,
i would suppose more something like:
**Packages**
- cri-o-1.8
**versions**
  - 1.8-0\~ubuntu16.04.2~ppa1
  - 1.8-1\~ubuntu16.04.2~ppa1
  - 1.8-2\~ubuntu16.04.2~ppa1
  - 1.8-3\~ubuntu16.04.2~ppa1
  - 1.8-4\~ubuntu16.04.2~ppa1
  - 1.8-5\~ubuntu16.04.2~ppa1
- cri-o-1.9
**versions**
  - 1.9-0\~ubuntu16.04.2~ppa1
  - 1.9-1\~ubuntu16.04.2~ppa1
  - 1.9-2\~ubuntu16.04.2~ppa1
  - 1.9-3\~ubuntu16.04.2~ppa1

So having a separate package for each minor version.
Would this be possible?

Background:
We're supporting cri-o as container-runtime in our kubernetes machine-controller: https://github.com/kubermatic/machine-controller 
We install cri-o via cloud-init from the Ubuntu repository. But since the package in the Repository is called just `cri-o` we need to pin the version so we do not end up with an unsupported setup (kubernetes 1.9+cri-o 1.10 - for example)
https://github.com/kubermatic/machine-controller/blob/master/pkg/userdata/ubuntu/crio.go

**Comment by lsm5** [comment]
so I'm told upstream supports the latest from `release-1.[7,8,9]` branches. so I can get separate packages going for each of those, but maintaining debs for every minor release (1.9.2, 1.9.3 etc.) seems like a bad idea.

**Comment by mrunalp** [comment]
@lsm5 Is there anyway we can automate pushing new debians? We can write a cron job which can look for latest tags and can build and push.

**Comment by lsm5** [comment]
@mrunalp I guess I'll need to get the deb packaging files merged in the 1.[7,8,9] branches first, I did open a PR for master branch, but seems like that's the wrong place for it. Once that's done, as long as some CI can provide a xenial instance (probably not Travis which uses an older LTS version), we should be good to go. I might also need to setup a bot email address for GPG signing builds I guess.

**Comment by lsm5** [comment]
i have a builder script for this, let me try and generalize it a bit, still trying to get the hang of debian changelog editors

**Comment by alvaroaleman** [comment]
At the end of the day what is needed is a way to automatically install a cri-o `v1.X.Whatever-i-dont-care`. Would it be feasible to just have a metapackage `cri-o-v1.9` that depends on the latest `crio-o` package of the `1.9` tree?

**Comment by mrIncompetent** [comment]
@alvaroaleman thats whats currently planned afaik.

But: Please do not deleted old versions. Otherwise people will not be able to roll back in case they encounter a critical bug in the latest version.

**Comment by lsm5** [comment]
@alvaroaleman see: https://launchpad.net/~projectatomic/+archive/ubuntu/ppa/+packages for cri-o-1.9 package.

@mrIncompetent When you submit a new build to the PPA, the older build gets deleted. This is in sync with upstream saying they only support the latest releases in the 1.7, 1.8 and 1.9 branches.

So, once there's 1.9.8 in PPA, if you want the older build of 1.9.7, there's no way to do this apart from having separate packages: cri-o-1.9.8 and cri-o-1.9.7 and so on. If there's something in PPA settings that allows to keep older builds that I missed, do let me know. So yes, there will be 2 extra packages `cri-o-1.7` and `cri-o-1.8` but I don't see the point in keeping multiple point releases of the same branch on the PPA unless upstream supports it too.

**Comment by umohnani8** [comment]
This seems resolved, please reopen if not. Closing for now.
