### ISSUE TITLE
cncf

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-sigs/cri-o#1422]
I keep seeing cncf level presentations show off containerd and rkt but not cri-o as its not a cncf level project. Should cri-o be moved from kubernetes-incubator to an incubation level project in the cncf? It would gain much more visibility then.

**Comment by rhatdan** [comment]
Sure we would love to have it moved there, but how does one do that?

**Comment by joejulian** [comment]
https://github.com/cncf/toc/blob/master/process/project_proposals.adoc

**Comment by umohnani8** [comment]
The proposal for getting cri-o into cncf: https://github.com/cncf/toc/pull/177

**Comment by rhatdan** [comment]
Since the proposal is upstream, no reason to keep this issue open.
