### ISSUE TITLE
Pod sandbox becomes SANDBOX_NOTREADY after four seconds

### ISSUE THREAD

**Issue by adelton** [kubernetes-sigs/cri-o#1432]
**Description**

I try to follow the examples at https://github.com/kubernetes-incubator/cri-tools/blob/master/docs/crictl.md. I create sandbox, it is reported as `SANDBOX_READY` but after a while it becomes `SANDBOX_NOTREADY`.

**Steps to reproduce the issue:**
1. Have Fedora 27 with `runc-1.0.0-17.rc4.git9f9c962.fc27.x86_64` and CRI-O and `crictl` built from their respective git masters.
2. Create file `podsandbox-config.json` with content
```
{
    "metadata": {
        "name": "nginx-sandbox",
        "namespace": "default",
        "attempt": 1,
        "uid": "hdishd83djaidwnduwk28bcsb"
    },
    "linux": {
    }
}
```
3. Create file `howto` with content
```
crictl runp podsandbox-config.json
crictl pods
sleep 4
crictl pods
```
4. Run `bash howto`.

**Describe the results you received:**

```
# bash howto 
396df39c7040b85f34a152b157988de01ff1bae3a233505ef43c4b60724088bf
PODSANDBOX ID       CREATED                  STATE               NAME                NAMESPACE           ATTEMPT
396df39c7040b       Less than a second ago   SANDBOX_READY       nginx-sandbox       default             1
PODSANDBOX ID       CREATED             STATE               NAME                NAMESPACE           ATTEMPT
396df39c7040b       4 seconds ago       SANDBOX_NOTREADY    nginx-sandbox       default             1
```

**Describe the results you expected:**

The sandbox stays in `SANDBOX_READY`

**Additional information you deem important (e.g. issue happens only occasionally):**

With `sleep 3` instead of `sleep 4`, the second `crictl pods` will sometimes still catch the pod as `SANDBOX_READY`. With `sleep 4`, I always see it as `SANDBOX_NOTREADY`.

There are no AVC denials, setting SELinux to permissive does not help.

CRI-O daemon is running as

```
system_u:system_r:container_runtime_t:s0 5989 ? Ssl   0:54 /usr/local/bin/crio
```

**Output of `crio --version`:**

```
crio version 1.10.0-dev
commit: "f7c1adf303b9380df5fe795ffa24b344ea70858b"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by adelton** [comment]
When I build CRI-O and `crictl` from their `release-1.9` branches, the `crictl runp` with the same `podsandbox-config.json` gives me stable pod sandbox which remains `SANDBOX_READY`.

So this looks like a regression in master.

**Comment by runcom** [comment]
do you have cri-o logs or journals from the system?

**Comment by mrunalp** [comment]
@adelton Can you try with this commit https://github.com/kubernetes-incubator/cri-o/blob/master/Dockerfile#L101? This is what cri-o master is using for testing right now.

**Comment by adelton** [comment]
With `cri-tools` commit 240a840375cdabb5860c75c99e8b0d0a776006b4 things work. Does this mean I should open the same issue against `cri-tools`?

**Comment by adelton** [comment]
By the way, when I rerun the same `crictl runp` command with the same `.json` which has the same `metadata/uid`, the pod gets recreated with different uid.

However, when I switch between CRI-O 1.9 and master and do the same, I get errors like

```
FATA[0000] run pod sandbox failed: rpc error: code = Unknown desc = pod sandbox with name "k8s_bash-sandbox_test-1_qoirewuqroweiunduwk28bcsb_1" already exists 
```

But `crictl pods` will not show that pod. Is that expected? Won't it cause issues during upgrade? If not expected, should I file it as separate issue?

**Comment by adelton** [comment]
Even if I now return to `crictl` from its master, I'm no longer able to reproduce the issue, to provide the journal logs.

**Comment by adelton** [comment]
I was now able to reproduce the error again, with CRI-O and `crictl` both built from their masters, and journal says

```
level=warning msg="no security context found in config."
level=info msg="Running conmon under slice  and unitName crio-conmon-f2c1033e544cb57788018d85e98a0c5a6d5709074a0fcf442b22fdc8fbbd53a1.scope"
level=warning msg="Failed to add conmon to systemd sandbox cgroup: Invalid unit name ''"
level=info msg="Got pod network {Name:nginx-sandbox Namespace:default ID:f2c1033e544cb57788018d85e98a0c5a6d5709074a0fcf442b22fdc8fbbd53a1 NetNS:/proc/32467/ns/net PortMappings:[]}"
level=info msg="About to add CNI network cni-loopback (type=loopback)"
level=info msg="Got pod network {Name:nginx-sandbox Namespace:default ID:f2c1033e544cb57788018d85e98a0c5a6d5709074a0fcf442b22fdc8fbbd53a1 NetNS:/proc/32467/ns/net PortMappings:[]}"
level=info msg="About to add CNI network crio-bridge (type=bridge)"
level=info msg="Got pod network {Name:nginx-sandbox Namespace:default ID:f2c1033e544cb57788018d85e98a0c5a6d5709074a0fcf442b22fdc8fbbd53a1 NetNS:/proc/32467/ns/net PortMappings:[]}"
level=info msg="About to del CNI network crio-bridge (type=bridge)"
level=warning msg="imageStatus: can't find k8s.gcr.io/pause-amd64:3.1"
level=warning msg="Stop container "5c77b5f7ddf12e5001b5b6b7a6fdbf7fbff059c76e30453b04e026482773d780" timed out: failed to wait process, timeout reached after 30 seconds"
```

**Comment by adelton** [comment]
The `Failed to add conmon to systemd sandbox cgroup: Invalid unit name ''` seems remotely similar to https://github.com/kubernetes-incubator/cri-o/issues/842. I use

```
# grep cgroup_manager /etc/crio/crio.conf
# cgroup_manager is the cgroup management implementation to be used
cgroup_manager = "systemd"
```

in my setup.

**Comment by Random-Liu** [comment]
@adelton I guess you might be using crictl to create pod/container on a running kubernetes node. Kubelet deletes unwanted containers/pods, please don't do that on a running kubernetes node.

See https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/#example-crictl-commands

**Comment by adelton** [comment]
It's been a while I file this ticket but I'm very very sure that there was no Kubernetes on the machine I was trying this on.

**Comment by umohnani8** [comment]
Tried this with cri-o 1.14.0 and the pod stays in Ready state after multiple `sleep` commands. @adelton please reopen this if you are still seeing this issue. Closing
