### ISSUE TITLE
Compatibility with past k8s versions

### ISSUE THREAD

**Issue by ijl** [kubernetes-sigs/cri-o#1482]
Could you please include more explicit documentation, beyond the compatibility matrix (https://github.com/kubernetes-incubator/cri-o#compatibility-matrix-cri-o---kubernetes-clusters), on whether cri-o will make any guarantees or effort on being able to run past versions of kubernetes? When can a breaking change be introduced?

**Comment by rhatdan** [comment]
I think the only thing we can guarantee is that the cri-o version matches the version of Kubernetes.  Kubernetes has made a few broken changes to CRI which CRI-O implemented.
