### ISSUE TITLE
run as pid2

### ISSUE THREAD

**Issue by vbatts** [kubernetes-sigs/cri-o#1498]
**Description**
This is a discussion topic, and if it is already a feature please close this issue.
Given the role of pid 1, despite the pattern of running containers with the command as pid 1 and may not be prepared to wait on children and handle zombies. Cri-o should have the ability, even if set as a global default, to run containers under a stub init whenever the arg[0] is not one of `/sbin/init` or `/usr/lib/systemd/systemd` or similar.

cc @poettering

**Comment by wking** [comment]
Some related discussion in #1242.  Although if the intention here is to install your own reaper without a pod-scoped PID namespace, this issue is distinct from the previous discussion.

**Comment by rhatdan** [comment]
Doesn't conmon already do reaping for you?

**Comment by wking** [comment]
On Wed, Apr 04, 2018 at 07:39:00PM +0000, Daniel J Walsh wrote:
> Doesn't conmon already do reaping for you?

I hope not ;).  How would it distinguish between “the container's init
doesn't know what it's doing” (where you'd want something CRI-O
specific to be able to step in an reap) and “the container's init
needs to monitor process exits and just hasn't gotten around to
reaping that particular process yet” (where you'd want CRI-O to leave
the process alone).

**Comment by rhatdan** [comment]
No action in another year.  I guess this is not something we need..  Reopen if you disagree.
