### ISSUE TITLE
Needless abuse of CPU resources during shutdown in crio-shutdown.service

### ISSUE THREAD

**Issue by ahkok** [kubernetes-sigs/cri-o#1534]
https://github.com/kubernetes-incubator/cri-o/blob/c24e0d9ee7f74082d1ddb6154e0ba3418b538276/contrib/systemd/crio-shutdown.service#L10

There's really no need to spawn a full bash to do this.

```
ExecStop=/usr/bin/mkdir /var/lib/crio
ExecStop=/usr/bin/touch /var/lib/crio/crio.shutdown
```

Making a folder without assigning permissions is dubious practice, too. Ideally, the program instead does `/usr/bin/touch /run/crio-shutdown` instead since that is removed automatically on reboot, and doesn't require `mkdir` at all, and would be much simpler.

**Comment by rhatdan** [comment]
@ahkok I can't remember the exact reason we made it on disk as opposed to making it on tmpfs.  
@mrunalp Could this be because we wanted to cleanup if something crashed?  Do you have any recollection?

**Comment by ahkok** [comment]
https://github.com/kubernetes-incubator/cri-o/commit/309667f5158e7e13a47f57d24f6b69ee97aed871

the service was broken because `mkdir` isn't an absolute path, and systemd requires that `ExecStart` and `ExecStop` entries start with `/`. The fix was probably made without spotting that error. The whole reason I'm here filing this bugreport is because I happened to have that older commit on my system, and `systemctl daemon-reload` loudly complains about this unit because of just that.

The method of `ExecStart=/usr/bin/true` ... `ExecStop=/usr/bin/touch /run/crio-shutdown` should be sufficient, though. I don't see any reason why `server/server.go` can't be modified to use `/run/crio-shutdown`. Someone needs to test that, though, but making this less complex seems highly preferable.

**Comment by rhatdan** [comment]
I am closing this as I believe it is fixed in current CRI-O.  Reopen if you disagree.
