### ISSUE TITLE
tests: Using "/tmp/*/crio.sock" as endpoint is deprecated, please consider using full url format "unix:///tmp/*/crio.sock"

### ISSUE THREAD

**Issue by edsantiago** [kubernetes-sigs/cri-o#1535]
Trying to get cri-o tests running; failing. Current setup is:
```
cri-o-1.10.0-24.gitc24e0d9.fc29.x86_64
cri-tools-1.0.0-14.gitf37a5a1.fc29.x86_64
```
One of the failures is easy to fix:
```
Using "/tmp/tmp.OhZDfLLazo/crio.sock" as endpoint is deprecated, please consider using full url format "unix:///tmp/tmp.OhZDfLLazo/crio.sock".
```
Solution:
```
 function crictl() {
-        "$CRICTL_BINARY" -r "$CRIO_SOCKET" -i "$CRIO_SOCKET" "$@"
+        "$CRICTL_BINARY" -r "unix://$CRIO_SOCKET" -i "unix://$CRIO_SOCKET" "$@"
 }
```
Since this isn't fixed already, it's likely that you guys haven't seen this failure yet. Filing as a heads-up for when you start seeing it.

**Comment by wking** [comment]
I guess #1353 missed this?  Do we want to prefix `CRIO_SOCKET` there, or set the prefix [when we define the variable][1]?  If `socat` can't handle the prefix (I don't know), then your suggested prefixing when invoking `CRICTL_BINARY` makes more sense.

Looking for other issues, I think some of the integration tests and other locations may also need updating:

```console
$ git grep 'crio\.sock' | grep -v unix://
contrib/test/integration/critest.yml:  shell: "critest --runtime-endpoint /var/run/crio/crio.sock --image-endpoint /var/run/crio/crio.sock v"
contrib/test/integration/critest.yml:  shell: "critest --runtime-endpoint /var/run/crio/crio.sock --image-endpoint /var/run/crio/crio.sock --ginkgo.skip='should not allow privilege escalation when true'"
contrib/test/integration/critest.yml:  shell: "critest --runtime-endpoint /var/run/crio/crio.sock --image-endpoint /var/run/crio/crio.sock --benchmark"
contrib/test/integration/main.yml:        crio_socket: "/var/run/crio.sock"
contrib/test/integration/main.yml:          crio_socket: "/var/run/crio/crio.sock"
contrib/test/integration/main.yml:          crio_socket: "/var/run/crio/crio.sock"
crictl.yaml:runtime-endpoint: /var/run/crio/crio.sock
docs/crio.8.md:**--listen**="": Path to CRI-O socket (default: "/var/run/crio/crio.sock")
docs/crio.conf.5.md:  Path to crio socket (default: "/var/run/crio/crio.sock")
server/config.go:                       Listen:        "/var/run/crio/crio.sock",
server/config_test.go:          {c.APIConfig.Listen, "/var/run/crio.sock"},
server/fixtures/crio.conf:listen = "/var/run/crio.sock"
test/helpers.bash:CRIO_SOCKET="$TESTDIR/crio.sock"
tutorial.md:sudo crictl --runtime-endpoint /var/run/crio/crio.sock info
tutorial.md:> you can export $CRI_RUNTIME_ENDPOINT=/var/run/crio/crio.sock
```

Maybe #1353 only updated kublet consumers and now we need to get crictl consumers?  I think it's probably best to just update all of these locations in one swoop.

[1]: https://github.com/kubernetes-incubator/cri-o/blob/733d791bec7792b25137eaf432ab974c5f2f9bc4/test/helpers.bash#L93

**Comment by edsantiago** [comment]
>  Do we want to prefix CRIO_SOCKET there, or set the prefix when we define the variable? 

That was my first attempt, because duplication is evil. Neither socat nor crio itself grokked it.

**Comment by wking** [comment]
> > Do we want to prefix CRIO_SOCKET there, or set the prefix when we define the variable?
>
> That was my first attempt, because duplication is evil. Neither socat nor crio itself grokked it.

Should we teach `crio` about it?

**Comment by edsantiago** [comment]
I would give that a big yes; my only caveat is that it may have already been done: I haven't taken the time to look at the sources  to see if it's already been done. This seems so obvious (and blocking) that I would expect it to already have been done, at least on a side branch.

**Comment by wking** [comment]
#1543 just landed with at least one of the changes needed for this issue.

**Comment by rhatdan** [comment]
I am closing this since I think it is fixed.  Reopen if you disagree.
