### ISSUE TITLE
clean up pointer struct relationships

### ISSUE THREAD

**Issue by vbatts** [kubernetes-sigs/cri-o#1551]
**Description**

Spinning off from:
* https://github.com/kubernetes-incubator/cri-o/pull/1439#discussion_r185821385
* https://github.com/kubernetes-incubator/cri-o/pull/1439#discussion_r185840215

https://github.com/kubernetes-incubator/cri-o/blob/4e6919c593644839728dbb4b35414cd7ac09114a/lib/sandbox/sandbox.go#L396
Returns potentially nil object of a struct that has functions. 
So now that nil structs functions ought to check whether the instance of the struct their a member of is even nil?
It's a nasty pattern.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@vbatts is this still something we need?

**Comment by vbatts** [comment]
Not until it bites someone 🤓
