### ISSUE TITLE
cannot execute cri-o tests using devicemapper and specifying a block device

### ISSUE THREAD

**Issue by chavafg** [kubernetes-sigs/cri-o#1576]
**Description**

I've been trying to execute the cri-o tests (`ctr.bats`) using `devicemapper` and specifying a block device. 
The first test passes correctly, but when starting the second one, the test fails when calling the `bin2img` 
(https://github.com/kubernetes-incubator/cri-o/blob/master/test/helpers.bash#L225) with this error:

```
 time="2018-05-22T23:28:31Z" level=error msg="error opening storage: /dev/sdc is already part of a volume group "storage": must remove this device from any volume group or provide a different device"
```

**Steps to reproduce the issue:**
1. Build CRI-O master branch 
2. Use these storage options: `export STORAGE_OPTIONS="--storage-driver devicemapper --storage-opt dm.directlvm_device=/dev/sdc --storage-opt dm.directlvm_device_force=True --storage-opt dm.thinp_percent=95 --storage-opt dm.thinp_metapercent=1 --storage-opt dm.thinp_autoextend_threshold=80 --storage-opt dm.thinp_autoextend_percent=20"`
Needed to create a physical voluime on /dev/sdc/: `pvcreate /dev/sdc`

3.  run the tests:`cd $GOPATH/src/github.com/kubernetes-incubator/cri-o/test/ && ./test_runner.sh ctr.bats`

**Describe the results you received:**
```
++ time bats --tap ctr.bats
1..32
ok 1 ctr not found correct error message
not ok 2 ctr termination reason Completed
# (from function `start_crio' in file helpers.bash, line 225,
#  in test file ctr.bats, line 19)
#   `start_crio' failed
# time="2018-05-22T23:28:31Z" level=error msg="error opening storage: /dev/sdc is already part of a volume group "storage": must remove this device from any volume group or provide a different device"
# 2018/05/22 23:28:31 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /tmp/tmp.o1Kq2N47eC/crio.sock: connect: no such file or directory"; Reconnecting to {/tmp/tmp.o1Kq2N47eC/crio.sock <nil>}
# time="2018-05-22T23:28:31Z" level=fatal msg="listing containers failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable"
# 2018/05/22 23:28:31 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /tmp/tmp.o1Kq2N47eC/crio.sock: connect: no such file or directory"; Reconnecting to {/tmp/tmp.o1Kq2N47eC/crio.sock <nil>}
# time="2018-05-22T23:28:31Z" level=fatal msg="listing pod sandboxes failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable"
# 0
```

**Describe the results you expected:**
`bin2img` should be able to reuse the same block device that was used for test number 1. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
```
$ crio --version
crio version 1.11.0-dev
commit: "6d98a70f1fd05d1ed4183a5e9dd36e0811008ad1"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by rhatdan** [comment]
@rhvgoyal Any ideas?

**Comment by rhatdan** [comment]
So to fix this we shold remove the thinpool?

**Comment by nalind** [comment]
Adding
```
        lvm lvremove -y storage/thinpool
        lvm vgremove -y storage
        lvm pvremove -y /dev/sdc
```
right before the `rm -rf "$TESTDIR"` in cleanup_test() seems to help when I try it, but it's hardly a general solution.

**Comment by rhatdan** [comment]
Well we could add a storage_cleanup and then ignore failures.  I will add this to my PR to see if it fixes the kata containers problem.

**Comment by sboeuf** [comment]
@rhatdan if you add this to your PR, and that we merge https://github.com/kata-containers/tests/pull/342, it should be okay. Otherwise, you'll have only one part of the fix here.
@chavafg could you confirm that you get CRI-O testing for Kata properly passing if you apply what @nalind has suggested ?

**Comment by chavafg** [comment]
I confirm that the tests pass properly applying what @nalind suggested and https://github.com/kata-containers/tests/pull/342

**Comment by mrunalp** [comment]
@chavafg Thanks! @nalind Could we add a storage_driver specific cleanup code to the tests which will be empty for the other drivers but execute what you suggested for devicemapper?

**Comment by rhatdan** [comment]
@nalind Did you ever work on this?
@chavafg is this something I can close now?

**Comment by chavafg** [comment]
Yes, we can close this, it is working now.
