### ISSUE TITLE
conmon binary path should be consistent in crio.conf and conmon rpm spec for Fedora

### ISSUE THREAD

**Issue by pravisankar** [kubernetes-sigs/cri-o#1595]
**Description**
Installed cri-o, conmon on Fedora 27 and running openshift with crio runtime failed with 'desc = fork/exec /usr/local/libexec/crio/conmon: no such file or directory'. This happened because of inconsistency between where the rpm is installing the conmon binary and the default conmon path set in crio.conf

[root@openshift-node-1 /]# rpm -qa | grep conmon
conmon-1.10.0-4.git623b502.fc27.x86_64
[root@openshift-node-1 /]# rpm -qa | grep cri-o
cri-o-1.10.0-4.git623b502.fc27.x86_64

[root@openshift-node-1 /]# crio --version
crio version 1.10.0
commit: "1317d05da4b526099a4feaf30f871af29fa6ed89-dirty"

[root@openshift-node-1 /]# rpm -ql conmon-2:1.10.0-4.git623b502.fc27.x86_64
...
/usr/libexec/crio/conmon
...

[root@openshift-node-1 /]# cat /etc/crio/crio.conf | grep conmon
...
conmon = "/usr/local/libexec/crio/conmon"
...

**Comment by rhatdan** [comment]
There should be no "local" content in the image that we ship.

**Comment by lsm5** [comment]
@pravisankar could you check if you have a /etc/crio/crio.conf.rpmnew by any chance? Also, the cri-o version you mention is older than what's in stable. Can you please fetch the latest in stable (1.10.1-1) and let me know if it still persists?

**Comment by rhatdan** [comment]
Could you update to cri-o-1.10.1-1.git728df92.fc27 and see if that works correctly?

**Comment by umohnani8** [comment]
@pravisankar please reopen if you are still seeing this issue. closing.
