### ISSUE TITLE
Disable crond on CRI-O CI systems

### ISSUE THREAD

**Issue by cevich** [kubernetes-sigs/cri-o#1624]
While debugging another problem, noticed the ``cron.daily`` jobs running ***while*** the Ansible playbook was executing tests.  This is most certainly not, ever, desirable.  Either the playbooks, or OriginCI should probably completely disable crond.  At a minimum, delete all ``/etc/cron.*/*`` (after all packages are installed).

**Comment by cevich** [comment]
@edsantiago wanna fix this one?  Should be easy :smile:

**Comment by cevich** [comment]
Example (from job 1081):

```
Jun 14 18:02:02 ip-172-18-5-4.ec2.internal crio[1204]: time="2018-06-14 18:02:02.820438033Z" level=info msg="About to del CNI network crio-bridge (type=bridge)"
Jun 14 18:02:02 ip-172-18-5-4.ec2.internal crio[1204]: time="2018-06-14 18:02:02.825836990Z" level=error msg="Error deleting network: failed to Statfs "/proc/10855/ns/net": no such file or directory"
Jun 14 18:02:02 ip-172-18-5-4.ec2.internal crio[1204]: time="2018-06-14 18:02:02.825871626Z" level=warning msg="failed to destroy network for pod sandbox k8s_kube-dns-659bc9899c-v65q5_kube-system_0d4c8e23-6ff1-11e8-8aa9-0e9d1a476612_0(2693a5eaf350443425c9de889eaf5911b16d40166eafc5145ccde4563d6ded78): failed to Statfs "/proc/10855/ns/net": no such file or directory"
Jun 14 18:14:57 ip-172-18-5-4.ec2.internal systemd[1]: Starting Cleanup of Temporary Directories...
Jun 14 18:14:57 ip-172-18-5-4.ec2.internal systemd[1]: Started Cleanup of Temporary Directories.
Jun 14 18:17:01 ip-172-18-5-4.ec2.internal anacron[4515]: Job `cron.daily' started
Jun 14 18:17:01 ip-172-18-5-4.ec2.internal run-parts(/etc/cron.daily)[7158]: starting logrotate
Jun 14 18:17:01 ip-172-18-5-4.ec2.internal run-parts(/etc/cron.daily)[7163]: finished logrotate
Jun 14 18:17:01 ip-172-18-5-4.ec2.internal run-parts(/etc/cron.daily)[7165]: starting man-db.cron
Jun 14 18:17:02 ip-172-18-5-4.ec2.internal run-parts(/etc/cron.daily)[7174]: finished man-db.cron
Jun 14 18:17:02 ip-172-18-5-4.ec2.internal run-parts(/etc/cron.daily)[7176]: starting mlocate
Jun 14 18:17:05 ip-172-18-5-4.ec2.internal run-parts(/etc/cron.daily)[7199]: finished mlocate
Jun 14 18:17:05 ip-172-18-5-4.ec2.internal run-parts(/etc/cron.daily)[7201]: starting rhsmd
Jun 14 18:17:06 ip-172-18-5-4.ec2.internal rhsmd[7204]: In order for Subscription Manager to provide your system with updates, your system must be registered with the Customer Portal. Please enter your Red Hat login to ensure your system is up-to-date.
Jun 14 18:17:06 ip-172-18-5-4.ec2.internal run-parts(/etc/cron.daily)[7211]: finished rhsmd
Jun 14 18:17:06 ip-172-18-5-4.ec2.internal anacron[4515]: Job `cron.daily' terminated
Jun 14 18:23:50 ip-172-18-5-4.ec2.internal dhclient[799]: DHCPREQUEST on eth0 to 172.18.0.1 port 67 (xid=0x42a10d3b)
```

**Comment by edsantiago** [comment]
My best guess is that this should be done in `kommandir/roles/services/defaults/main.yml` by adding `crond` to `disabled_services`. But I'm stuck because I can't figure out where this playbook is run (komandir, or the slaves) or even if this code works, since all the variables are empty.

**Comment by cevich** [comment]
@edsantiago oh, easy fix: that's the wrong repo :smile:     The code you're looking for is under here:

https://github.com/kubernetes-incubator/cri-o/tree/master/contrib/test/integration/

**Comment by cevich** [comment]
Execution happens from Jenkins jobs generated from https://github.com/openshift/aos-cd-jobs within ``sjb/config/common/test_cases/crio.yml`` and ``sjb/config/common/test_cases/*crio*.yml``.
One-off test-jobs can be derived from the production jobs to exercise changes.

If the changes are/can be confined to just the cri-o repo, testing them is easier.  Just mention ``/test ami`` or ``/test all`` in the PR and that will trigger it.

**Comment by cevich** [comment]
Oh, and @edsantiago the spot you found in ADEPT seems good/correct.  I'd accept a PR there as well, if you have a mind for it.  Important thing is here though, in the CRI-O repo.

**Comment by umohnani8** [comment]
@edsantiago @cevich is this done?

**Comment by cevich** [comment]
@umohnani8 I believe this was never fixed, however I'm not sure if it's still a problem or not.  We can close for now, pending new evidence either way.
