### ISSUE TITLE
CRI-O is not creating containers as per the specified annotation in the yaml file.

### ISSUE THREAD

**Issue by yadavkkumar** [kubernetes-sigs/cri-o#1637]
**Description**

I am using kata-containers with kubernetes, whenever i do a `kubeadm init`, then cri-o should create all the containers in runc runtime only. As all these containers are trusted so cri-o should create them in runc runtime only but some of the containers like kube-dns, it is creating in kata-runtime. Which is not the proper behaviour to create the trusted containers.

Other issue is whenever i am trying to create any container with the annotation as trusted and untrusted, they all are started in kata-runtime only.
According to my information, trusted containers should run with runc runtime while untrusted should run with kata-runtime. But they all are starting using kata-runtime irrespective of the annotation specified (Trusted and Untrusted).

I am trying with the following annotations
`io.kubernetes.cri.untrusted-workload: "false"`
`io.kubernetes.cri-o.TrustedSandbox: "true"`

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
`kubeadm init` starting some of the containers using runc and some using kata-runtime.
```
ALL THESE CONTAINERS ARE CREATED WITH RUNC RUNTIME.
etcd   
kube-apiserver 
kube-controller-manager  
kube-proxy
kube-scheduler
weave-net
```
BUT THIS `kube-dns`  IS CREATED USING KATA-RUNTIME.

**Describe the results you expected:**
kubeadm init should start all the containers(kube-apiserver, kube-controller-manager, kube-proxy, 
kube-scheduler, weave-net and kube-dns ) as trusted and using runc runtime only.

While it should create all other containers as per the specified annotations (trusted and Untrusted).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.11.0-dev
commit: "f64f5b8a732d51fc7a5096cb53da5a9d54eb3a0d"

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
```
Linux tcs07 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 6_64 x86_64 GNU/Linux
```

- **Others**:
```
crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.11.0-dev
RuntimeApiVersion:  v1alpha1
```
/bug

**Comment by rhatdan** [comment]
I would figure this is fixed by now.  If not reopen the issue.
