### ISSUE TITLE
Moving this repository to kubernetes-sigs organization

### ISSUE THREAD

**Issue by runcom** [kubernetes-sigs/cri-o#1639]
The kubernetes-incubator project is now deprecated. Given CRI-O is considered stable at this point, with 3 major, fully supported, releases and given the users and contributors we've gathered over time, I propose to move CRI-O under the kubernetes-sigs organization on GitHub.

@mrunalp @derekwaynecarr @rhatdan @kubernetes-incubator/maintainers-cri-o et all, what do you think?

**Comment by rhatdan** [comment]
I agree.
:+1:

**Comment by dchen1107** [comment]
I agreed.

**Comment by derekwaynecarr** [comment]
Discussed during SIG Node call on 7/10 call, I agree this should move under kubernetes-sigs org.

**Comment by mikebrow** [comment]
Some comments:
If not there.. where? 
Not sure what it means to be in "kubernetes-sigs org." 
The "Org for Kubernetes SIG-related work," is a bit broad. 
Would be nice if we had a sig-cri and/or a sig-container-runtimes as sig-node is also a bit broad.

**Comment by derekwaynecarr** [comment]
@mikebrow 

see definition of sig sponsored repositories here:
https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#sig-repositories

**Comment by runcom** [comment]
process started here https://github.com/kubernetes/org/issues/60

**Comment by runcom** [comment]
:+1:

**Comment by mikebrow** [comment]
https://github.com/kubernetes/community/pull/2624/files merged, my question resolved :-)

**Comment by runcom** [comment]
clearly done now, thanks everyone 🎉
