### ISSUE TITLE
crictl pull nginx:latest failed

### ISSUE THREAD

**Issue by jackzhanghk** [kubernetes-sigs/cri-o#1685]
**Description**

**Comment by jackzhanghk** [comment]
I pull image faild, crio crictl info list:
crictl version                                                                                 
DEBU[0000] VersionRequest: &VersionRequest{Version:v1alpha2,} 
DEBU[0000] VersionResponse: &VersionResponse{Version:0.1.0,RuntimeName:cri-o,RuntimeVersion:1.11.0-dev,RuntimeApiVersion:v1alpha1,} 
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.11.0-dev
RuntimeApiVersion:  v1alpha1

cat /etc/crictl.yaml                                                                           
runtime-endpoint: unix:///var/run/crio/crio.sock
image-endpoint: unix:///var/run/crio/crio.sock
timeout: 10
debug: true

crictl pull nginx:latest                                                                              
DEBU[0000] PullImageRequest: &PullImageRequest{Image:&ImageSpec{Image:nginx:latest,},Auth:nil,SandboxConfig:nil,} 
DEBU[0000] PullImageResponse: nil                       
FATA[0000] pulling image failed: rpc error: code = Unknown desc = Invalid image name "docker.io/library/nginx:latest", unknown transport "docker.io/library/nginx"

crictl pull docker.io/library/nginx:latest                                       
DEBU[0000] PullImageRequest: &PullImageRequest{Image:&ImageSpec{Image:docker.io/library/nginx:latest,},Auth:nil,SandboxConfig:nil,} 
DEBU[0000] PullImageResponse: nil                       
FATA[0000] pulling image failed: rpc error: code = Unknown desc = Invalid image name "docker.io/library/nginx:latest", unknown transport "docker.io/library/nginx"

**Comment by umohnani8** [comment]
Tried with cri-o 1.14.0 and it works fine
```
sudo crictl pull docker.io/library/nginx
Image is up to date for docker.io/library/nginx@sha256:082b7224e857035c61eb4a802bfccf8392736953f78a99096acc7e3296739889
➜  cri-o git:(master) ✗ sudo crictl images | grep nginx
docker.io/library/nginx             latest              8c9ca4d17702c       113MB
```
@jackzhanghk please reopen if the issue persists for you.
