### ISSUE TITLE
[RFC] Define a generic API for VM based runtimes

### ISSUE THREAD

**Issue by sboeuf** [kubernetes-sigs/cri-o#1704]
__Why?__

With the recent [proposal](https://github.com/containerd/containerd/issues/2426) from `containerd` to facilitate how things are managed for VM based runtimes, by providing a new API allowing for a unique `containerd-shim` to manage a pod (instead of a container), I think this would be appropriate to find a global/generic API that could fit both `CRI-containerd/containerd` and `CRI-O`.
The main idea behind this API is to avoid any assumption that the container process is running on the host and that we can monitor it through its PID. Instead, the API provides all the expected entry points to get the answer about the container, without knowing how those information are going to be retrieved.
Also, the second point very interesting about this API would be to assume that the pod (VM in this case) will be managed by only one process running for its entire lifetime. This allows for enhancements regarding the states and information about the pod and its container which don't need to be stored on-disk since they could now be simply kept in-memory.

__How?__

After some preliminary talk with @mrunalp, he told me that gRPC brings a lot of memory consumption compared to the simple spawning of a binary (as done currently). That's why we could try to define the API itself, without providing a specific way of implementing it (gRPC server to expose the API can be optional).
I think the current API as defined in the [proposal](https://github.com/containerd/containerd/issues/2426) is completely fine.
Now, how can we, in `CRI-O`, leverage this API without a server exposing/implementing it ? I think the only way would be to have `CRI-O` directly calling into this API by relying on the implementation of it, that could be defined as a `plugin`.
And basically, as a configuration option, we could define if we want to use CRI-O with or without this interface. In case the interface would be chosen, `CRI-O` would not invoke `conmon`, and it would become the long running process taking care of each pod through this API.

__Thoughts__

There's one drawback with this approach, by not defining the way the API is exposed, we'll end up forcing each VM based runtime to implement two versions of this API (one for CRI-O and one for containerd), since they would be slightly different in the way they would handle things. And this would affect the benefits of defining an interface, particularly if there are several ways to implement it.

__Other options__
Lighter protocols that would allow to follow the same model of running one process per pod, exposing the API exactly as it would be done with gRPC server. Anything in mind ?

**Comment by mrunalp** [comment]
:+1: to defining an API.

**Comment by fabiand** [comment]
Side note, in this gist I tried to outline how device plugins could work better for hypervisor runtimes as well: https://gist.github.com/fabiand/81beda6550fae5731fd7e1a1ad48cc73

**Comment by cyphar** [comment]
I think if we're going to do this, inclusion into OCI and how the runtime-spec should evolve should be a very important part of the discussion. After all, if it's necessary to build something on top of the OCI spec that the OCI spec should already be doing -- maybe we need to improve the OCI spec so it caters for that need.

**Comment by cyphar** [comment]
@fabiand In the context of devices, I would recommend taking a look at how LXD (and LXC of course) has solved this problem.

**Comment by fabiand** [comment]
@cyphar do you have a pointer to that work?

**Comment by cyphar** [comment]
I believe the code would be [here](https://github.com/lxc/lxd/blob/lxd-3.5/lxd/devices.go) -- but if you want a more in-depth explanation I would recommend talking to @brauner, @stgraber and/or @3XX0.

**Comment by fabiand** [comment]
Thanks, IIUIC then it is per device type handling (beyond other things), which I agree with.

**Comment by rhatdan** [comment]
@sboeuf Is this still an issue or has this been done?

**Comment by sboeuf** [comment]
This has been implmented and merged already!
