### ISSUE TITLE
RuntimeHandler support

### ISSUE THREAD

**Issue by tallclair** [kubernetes-sigs/cri-o#1751]
As part of the new Kubernetes [RuntimeClass](https://github.com/kubernetes/community/blob/master/keps/sig-node/0014-runtime-class.md) feature, we added a new field to the CRI's RunPodSandboxRequest: `runtime_handler` (https://github.com/kubernetes/kubernetes/pull/67518).

As discussed in the proposal (under [RuntimeHandler](https://github.com/kubernetes/community/blob/master/keps/sig-node/0014-runtime-class.md#runtime-handler)), this new field is designed to select between multiple "handler" configurations, and deprecate the binary "trusted" and "untrusted" runtime selection.

In order to support this new feature, the following items need to be addressed:

- [ ] Map the `runtime_handler` field to a runtime configuration, deprecating the `io.kubernetes.cri-o.TrustedSandbox` annotation.
- [ ] Reject requests that cannot be mapped to a valid runtime configuration
- [ ] (optional) Support multiple (non-binary) named runtime configurations

### Proposal

1. Deprecate [`lib/Config.RuntimeUntrustedWorkload`](https://github.com/kubernetes-incubator/cri-o/blob/b6c5cafeffa9b3cde89812207b29ccedd3102712/lib/config.go#L112). If it is provided, give it the implicit configuration name of `untrusted`.
    - Deprecate [`lib/Config.DefaultWorkloadTrust`](https://github.com/kubernetes-incubator/cri-o/blob/b6c5cafeffa9b3cde89812207b29ccedd3102712/lib/config.go#L132).
    - (optional) Deprecate the [`lib/Config.Runtime`](https://github.com/kubernetes-incubator/cri-o/blob/b6c5cafeffa9b3cde89812207b29ccedd3102712/lib/config.go#L110) field as well, favoring a runtime with the name of `default` (or, repurpose the field to refer to the name of a runtime in the `Runtimes` list)
2. Introduce a new field: `Runtimes map[string]string`
    - The key is the runtime_handler, the value is the runtime binary
    - Specifying both the deprecated `RuntimeUntrustedWorkload` and a `Runtimes['untrusted']` is a configuration error (ditto for default, if we go that route).
3. Plumb the runtime config map & runtime handler through to the necessary places.
    - Return an error if the runtime handler does not map to a valid configuration
    - If both the untrusted annotation & runtime_handler are specified, prefer the runtime handler

**Comment by amshinde** [comment]
@tallclair We talked about following scenarios:
1. pass the runtime name to CNI
2. pass the runtime "type" to CNI (native, virtual, ...)
3. pass the network type to CNI (veth, vhost)

We dont want 1)  so that CNI does not have to deal with specific runtime names.
Between 2 and 3, I think 2) makes the most sense to me. CNI plugin can setup the network based on whether it is dealing with a network namespace or a hypervisor.

I am not in favor of 3, as I dont think CRI should know about what interfaces need to be created. Again if this is added as part of the CRI configuration, this would need to be changed for every CNI.

**Comment by tallclair** [comment]
I don't really like 2 (runtime type), since it requires us to come up with a classification scheme of all runtimes, but really what you're classifying is just the type of network it needs (option 3). Option 1 doesn't necessarily mean the CNI binary needs to understand runtime names, it would just mean that it needs to handle multiple named configurations, and select between them (similar to what is being proposed for CRI-o in this issue)

**Comment by amshinde** [comment]
@tallclair Ok with 1, it sounds like we would need to add support in CNI to handle different configurations based on runtimes.

**Comment by egernst** [comment]
@ruijingguo @amshinde - this discussion is probably more relevant on https://github.com/kubernetes-incubator/cri-o/issues/1733, right?

**Comment by egernst** [comment]
@tallclair this proposal makes sense to me.

**Comment by amshinde** [comment]
@egernst Yes, its more relevant for #1733. I meant to add my comments there instead. @ruijingguo lets move the discussion there.
