### ISSUE TITLE
Support returning the container pid in the ContainerStatus info map

### ISSUE THREAD

**Issue by dlespiau** [kubernetes-sigs/cri-o#1752]
I'd love to be able to retrieve the process pid from the ContainerStatus to be able to correlate containers with a process tree. This is to support tooling such as [Scope](https://github.com/weaveworks/scope).

Containerd has something along those lines: https://github.com/containerd/cri/blob/master/pkg/server/container_status.go#L102.

Now, the CRI interface doesn't seem to define any well-known keys and values for this info map:
```
message ContainerStatusResponse {
    // Status of the container.
    ContainerStatus status = 1;
    // Info is extra information of the Container. The key could be arbitrary string, and
    // value should be in json format. The information could include anything useful for
    // debug, e.g. pid for linux container based container runtime.
    // It should only be returned non-empty when Verbose is true.
    map<string, string> info = 2;
}
```
It'd be beneficial to standardise/define a bit of this. From what I gather from the containerd implementation, there's an `"info"` key with a serialized JSON object as value. That JSON object contains the `"pid"` key, along with a lot more details.

**Comment by mrunalp** [comment]
@dlespiau Sure, sounds good. I will make a PR to add that.

**Comment by huzhou** [comment]
Do we have release for this feature? We are looking for PID info.

**Comment by haircommander** [comment]
@huzhou every release past 1.12.0 should have it :)
