### ISSUE TITLE
Ubuntu Bionic 18.04: Missing cri-o packages from PPA

### ISSUE THREAD

**Issue by fjudith** [kubernetes-sigs/cri-o#1760]
**Description**

Only Ubuntu Xenial (16.04) of cri-o-1.10.0 and cri-o-1.11.0 are available on the PPA.
https://launchpad.net/~projectatomic/+archive/ubuntu/ppa

It will be great to have packages for latest Ubuntu Bionic (18.04) as well

**Comment by runcom** [comment]
@lsm5 ptal

**Comment by fhemberger** [comment]
@lsm5 Could you please update the PPA to include v1.13.x?

**Comment by jqueuniet** [comment]
It seems the PPA was updated with Bionic packages for versions of cri-o up to 1.13, but I'd also like to ask if a Bionic cri-tools package is also planned, as it would be very helpful for kubespray support.

**Comment by lsm5** [comment]
On Wed, Jan 23, 2019 at 02:34:51PM +0000, Johann Queuniet wrote:
> It seems the PPA was updated with Bionic packages for versions of cri-o up to 1.13, but I'd also like to ask if a Bionic cri-tools package is also planned, as it would be very helpful for kubespray support.

I'm on vacation until Monday. Shouldn't be a problem to make that available
though once I'm back.

I also have some WIP on snap package for skopeo. Plan to do the rest as well.

HTH.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes-sigs/cri-o/issues/1760#issuecomment-456823473

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by lsm5** [comment]
On Fri, Feb 01, 2019 at 05:45:49AM -0800, Pierre Margueritte wrote:
> Seems there are som issues with packages for CRI-O 1.13, they're almost empty:
> 
> ![screenshot 2019-02-01 at 14 44 13](https://user-images.githubusercontent.com/2368736/52126557-ecd1c680-262f-11e9-8ae4-5806e4e52bd8.png)
> 
> 

sorry about the delay, have been fighting other fires. Let me get on with
this...

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by lsm5** [comment]
On Fri, Feb 01, 2019 at 07:20:40PM +0530, Lokesh Mandvekar wrote:
> On Fri, Feb 01, 2019 at 05:45:49AM -0800, Pierre Margueritte wrote:
> > Seems there are som issues with packages for CRI-O 1.13, they're almost empty:
> > 
> > ![screenshot 2019-02-01 at 14 44 13](https://user-images.githubusercontent.com/2368736/52126557-ecd1c680-262f-11e9-8ae4-5806e4e52bd8.png)
> > 
> > 
> 
> sorry about the delay, have been fighting other fires. Let me get on with
> this...
> 

My rules file was referencing cri-o-1.12 as the buildroot dir, so no files were
actually getting installed, sorry about that.

I sent a cri-o-1.13 - 1.13.1-1~dev~ubuntu18.04~ppa2 to PPA, but it refuses to
build and doesn't show me failure logs either. I'm guessing something messed up
on their env itself. Should be fixed soon hopefully.


-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by rhatdan** [comment]
@lsm5 can I now close this issue?

**Comment by lsm5** [comment]
@rhatdan yes

**Comment by jqueuniet** [comment]
Should I open a separate issue for cri-tools? it doesn't seem like it's present for bionic in the repository, unless I'm mistaken.

**Comment by lsm5** [comment]
@jqueuniet yup, on the cri-tools repo, and copy me on it

**Comment by alexander255** [comment]
Sorry, for being a bother on this. But can with have a 1.14.* release of this on the PPA? (Works fine on Debian 10, btw!)
