### ISSUE TITLE
Unable to create pod sandboxes

### ISSUE THREAD

**Issue by bhperry** [kubernetes-sigs/cri-o#1766]
**Description**

I have a kubernetes cluster running with CRI-O, and one of the nodes is now failing to create sanboxes, and the kubelet logs have this error `devmapper: Thin Pool has 5833 free data blocks which is less than minimum required 7781 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior`. When I run, crictl sandboxes, there are many old sanboxes no longer in use that aren't getting cleaned up, some of which report status SANDBOX_NOTREADY. I deleted some of the sandboxes for pods that no longer exist, but I can't delete any of the SANDBOX_NOTREADY ones, and even some that are READY. Crictl just says `failed to remove pod sandbox d197c9cfc656d328d6de489437491bf4f4b4505064b96234104402e0539c9358: invalid argument`. Any idea what causes this, or how I can resolve it? I'm not actually super clear on what the thin pool is, but I'm guessing it has something to do with these configurations in crio.conf
```
    storage_driver = "devicemapper"

    # storage_option is used to pass an option to the storage driver.
    storage_option = [
      "dm.basesize=8G",
      "dm.directlvm_device=/dev/xvdc",
      "dm.directlvm_device_force=true",
      "dm.fs=ext4"
    ]
```

**Steps to reproduce the issue:**
1. Run kubernetes cluster with CRI-O runtime
2. Create and delete many pods(?)

**Describe the results you received:**
Crio starts failing to clean-up after itself, and runs out of space to create new sandboxes

**Describe the results you expected:**
No extra sandboxes sitting around, sandboxes not getting stuck in state SANDBOX_NOTREADY 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
```
    Version:  0.1.0
    RuntimeName:  cri-o
    RuntimeVersion:  1.9.7
    RuntimeApiVersion:  v1alpha1
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS m4.xlarge, CoreOS-stable-1688.5.3-hvm AMI, kubernetes 1.9.7

**Comment by bhperry** [comment]
Turns out it was from the devmapper volume being full of old images, due to ImageGC not working. I am still curious about why those pod sandboxes are stuck though.

**Comment by rhatdan** [comment]
@bhperry I am going to close this since there has been no issues for along time.
