### ISSUE TITLE
Pulling images from private registry over http

### ISSUE THREAD

**Issue by outcoldman** [kubernetes-sigs/cri-o#1768]
I have added private registry and insecure registry to the `crio.server`

```
ExecStart=/usr/bin/crio \
          --registry=10.0.2.2:5000 \
          --insecure-registry=10.0.2.2:5000 \
```

But when I try to pull the image I get

```
crictl -D pull 10.0.2.2:5000/myimage:5.0
DEBU[0000] PullImageRequest: &PullImageRequest{Image:&ImageSpec{Image:10.0.2.2:5000/myimage:5.0,},Auth:nil,SandboxConfig:nil,}
DEBU[0000] PullImageResponse: nil
FATA[0000] pulling image failed: rpc error: code = Unknown desc = Invalid image name "", expected colon-separated transport:reference
```

I tried to set the log-level to debug and found that crio tries to pull from https anyway. 

```
# crio -v
crio version 1.11.3-dev
commit: ""
```

So feels like that the real problem that there is no way to tell crio to use `http` protocol for registry.

**Comment by runcom** [comment]
> I tried to set the log-level to debug and found that crio tries to pull from http anyway.

can you paste the relevant debug output where you think crio is pulling http anyway? That can help diagnose the issue, the pull image error is different from what you're saying.

**Comment by outcoldman** [comment]
@runcom sorry, my misprint, it is pulling from `https`, while my registry is `http`, I will post a debug output in few days.

**Comment by runcom** [comment]
Thanks for the reproducer, I'll try it and see what's going on.

**Comment by runcom** [comment]
The first error you got is fixed:
```
FATA[0000] pulling image failed: rpc error: code = Unknown desc = Invalid image name "", expected colon-separated transport:reference
```
by https://github.com/kubernetes-incubator/cri-o/pull/1772/commits/3c6f266287c49636dfafd88c783c7d5353b829f6

I'm gonna try and fix and reproduce the other one

**Comment by runcom** [comment]
@outcoldman just saw that you're probably using master, could you test with #1772 (the latest commit) and see if it fixes it for you?

**Comment by uablrek** [comment]
Try it yourself in ~10 min if you use Ubuntu? see;
https://github.com/Nordix/xcluster

Or specifically; https://github.com/Nordix/xcluster/tree/master/ovl/private-reg

**Comment by rhatdan** [comment]
Looks like this is fixed?  Reopen if you disagree.

**Comment by skyend** [comment]
Works for me this

/usr/lib/systemd/system/crio.service
```
ExecStart=/usr/bin/crio \
          $CRIO_CONFIG_OPTIONS \
          $CRIO_RUNTIME_OPTIONS \
          $CRIO_STORAGE_OPTIONS \
          $CRIO_NETWORK_OPTIONS \
          $CRIO_METRICS_OPTIONS \
        --insecure-registry=10.10.0.7:5005
```

cri-o version
```
crio version 1.24.0
Version:          1.24.0
GitCommit:        0ba47c9b3e52eee95d898be84500c38c9fe032c9
GitTreeState:     clean
BuildDate:        2022-05-23T20:27:54Z
GoVersion:        go1.18.2
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        exclude_graphdriver_devicemapper, seccomp
SeccompEnabled:   true
AppArmorEnabled:  false
```

**Comment by seanmcconkey** [comment]
I'd been experiencing similar issues and while the above method for fixing this works, it's not ideal. Your changes to the service file could be over-written in an update and inserting those values across multiple K8s clusters isn't very agreeable.

The following is the correct way to do this.

Create a YAML file under `/etc/containers/registries.conf.d` and set prefix and location and insecure to 'true'.

eg. `registry.lab.net.yaml`

```
[[registry]]
prefix = "registry.lab.net"
insecure = True
blocked = false
location = "registry.lab.net"
```

Now restart the service.

```
systemctl daemon-reload
systemctl restart crio
```

Don't forget to copy your `ca.crt` to the following paths:

RHEL    : `/etc/pki/ca-trust/source/anchors/ca.crt`
Ubuntu : `/usr/local/share/ca-certificates/sudo`

And update your ca-trust.

RHEL    : `update-ca-trust`
Ubuntu : `update-ca-certificates`

Hopefully this will help many others not having to experience the pain of this.

**Comment by Nurlan199206** [comment]
> 

not working for me
