### ISSUE TITLE
Support For Windows Container

### ISSUE THREAD

**Issue by Jaspreetc** [kubernetes-sigs/cri-o#1779]
Will Windows Container be supported via CRI-O ?

**Comment by rhatdan** [comment]
You can not support Windows Containers on LInux systems, so unless someone picks up CRI-O support on WIndows boxes, NO.

We attempt to make sure CRI-O will build on non linux platforms but no one to my knowledge is working on Windows support.  But we would welcome it.

**Comment by Jaspreetc** [comment]
@taylorb-microsoft
Do you think this is going to happen?

@rhatdan 
Daniel, I wanted to understand from Open Shift point of View are we going with CRI-O in version 4.0 only or will Docker be there as a Container run time?

**Comment by rhatdan** [comment]
This issue was answered in the fall.
