### ISSUE TITLE
cgroupdriver has wrong default in package

### ISSUE THREAD

**Issue by ashcrow** [kubernetes-sigs/cri-o#1796]
Version: `1.11.3-2`

The default `cgroupdriver` is being set to `cgroupfs` in the configuration provided by the rpm package. This should in fact be `systemd` per discussion with @mrunalp. Can we get this modified and rebuilt?

/cc @yuqi-zhang

**Comment by mrunalp** [comment]
@lsm5 This is for our rpm builds.

**Comment by lsm5** [comment]
This change has been made on RHEL. I'm guessing we need the same thing on fedora as well?

**Comment by mrunalp** [comment]
@lsm5 Yes, we do.

**Comment by lsm5** [comment]
ack, updating the cri-o modules now...

**Comment by ashcrow** [comment]
Let us know when this lands

**Comment by rhatdan** [comment]
Fixed.
