### ISSUE TITLE
CRI-O does not report disk statistics via `ListContainerStats` CRI call

### ISSUE THREAD

**Issue by mfpierre** [kubernetes-sigs/cri-o#1800]
**Description**

`CRI-O` does not report disk usage statistic via the `ListContainerStats` rpc call.

In the container stat struct `writable_layer` is currently set to `nil` which cause to report `0` for `used_bytes` and `inodes_used`
https://github.com/kubernetes-sigs/cri-o/blob/4cd5a7c60349be0678d9f1b0657683324c1a2726/server/container_stats.go#L29

**Steps to reproduce the issue:**
You can observe the issue using `crictl -r unix:///var/run/crio/crio.sock stats` that is using `ListContainerStats` and will report zeroes for disk statistics:

**Describe the results you received:**
```
CONTAINER           CPU %               MEM                 DISK                INODES
226d6c4186105       4.81                126.3MB             0B                  0
4b4f4d525501c       0.20                33.66MB             0B                  0
5cb52ff953c2a       1.41                25.79MB             0B                  0
```

**Describe the results you expected:**
Using `containerd` will display disk usage statistics:
```
CONTAINER           CPU %               MEM                 DISK                INODES
28103c8d7ea02       1.51                28.56MB             32.77kB             9
95591751cd28c       3.88                39.46MB             36.86kB             9
a322d22343340       1.66                26MB                20.48kB             5
```

**Output of `crio --version`:**

```
crio version 1.11.3-dev
```

**Comment by runcom** [comment]
we're aware of this, we currently have stats for kube going through cadvisor but the plan is to, of course, move to the CRI calls.

**Comment by mfpierre** [comment]
@runcom that's what I assumed but couldn't find any documentation or issue aknowledging this was missing.

**Comment by runcom** [comment]
mmm yeah, maybe we don't have an issue open, I'll check and open one if there's not. Also, we're always welcoming contributions if you're up to :)

**Comment by rhatdan** [comment]
Looks like this has been completed in upstream.
