### ISSUE TITLE
update ocicni vendor

### ISSUE THREAD

**Issue by mythi** [kubernetes-sigs/cri-o#1809]
**Description**

Currently, it isn't possible to launch pods without a CNI that exposes eth0 in the pod (for instance 'loopback only'). The latest ocicni makes this possible (according 2d3ce4620eab521d3636d23f7e035dc0bfde7644). 

I started to work on the update but it brings in new containernetworking/cni version and API changes so I opened this for discussion/guidance.

**Comment by rhatdan** [comment]
I just merged this.
Thanks @mythi
