### ISSUE TITLE
Image Garbage Collection

### ISSUE THREAD

**Issue by bhperry** [kubernetes-sigs/cri-o#1810]
**Description**

Was running kubernetes/cri-o 1.9.7 for a while, and always saw "ImageGC not implemented" errors. We just ignored it and did manual imageGC (which is not fun). Recently we upgraded to kubernetes 1.11.3, and I was under the impression that ImageGC had been fixed (based on the change logs). I no longer see those errors I saw before, however after filling up my image volume to over 90%, garbage collection still does not happen. I even see "Image garbage collection succeeded" in the kubelet logs occasionally, but no old images get removed.

Is image garbage collection not supported by cri-o? Or is it just because we have our images stored in a devmapper thinpool instead of on the root volume?

**Steps to reproduce the issue:**
1. Install cri-o and kubernetes version 1.11.3
2. In crio.conf set
storage_option = [
  "dm.basesize=8G",
  "dm.directlvm_device=/dev/xvdc",
  "dm.directlvm_device_force=true",
  "dm.fs=ext4"
]
3. Fill up the image volume. 

**Describe the results you received:**
Kubelet never garbage collects images. It seems to only look at the available space on the root volume. That would be fine if the "minimum-image-ttl-duration" option in kubelet would work, but it doesn't seem to pay any attention to that either.

**Describe the results you expected:**
Old images that are no longer in use will get deleted.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.11.3
commit: "4fbb0226dd4114aabc5ed13e292179f00e0f8690-dirty"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS m5.xlarge, CoreOS-stable-1688.5.3-hvm, 20G /dev/xvdc volume for images, 15G root volume

**Comment by bhperry** [comment]
I have confirmed that the issue is caused by using a devmapper thinpool in crio to store images. Are there any plans to add support for kubelet to retrieve imagefs metrics about thinpool devices from crio?

**Comment by mrunalp** [comment]
@bhperry Yes, we do plan to implement the stats API.

**Comment by bhperry** [comment]
Great to hear. I would definitely like to go back to using a thinpool later down the line.
