### ISSUE TITLE
memory cgroup count leak?

### ISSUE THREAD

**Issue by aalubin** [kubernetes-sigs/cri-o#1839]
**Description**
Every time a new pod is created, the counter for memory slice in /proc/cgroups is increased by 2

**Steps to reproduce the issue:**
Running the following command
cat /proc/cgroups;crictl rm `crictl ps|grep filebeat|awk '{print $1}'`;sleep 3; cat /proc/cgroups
Replace filebeat with the pod of your choice

**Describe the results you received:**
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	12	16	1
cpu	5	25	1
cpuacct	5	25	1
blkio	6	25	1
**memory	8	32	1**
devices	10	55	1
freezer	11	16	1
net_cls	3	16	1
perf_event	7	16	1
net_prio	3	16	1
hugetlb	2	16	1
pids	9	15	1
rdma	4	1	1
abfd4d71b4a58
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	12	16	1
cpu	5	25	1
cpuacct	5	25	1
blkio	6	25	1
**memory	8	34	1**
devices	10	55	1
freezer	11	16	1
net_cls	3	16	1
perf_event	7	16	1
net_prio	3	16	1
hugetlb	2	16	1
pids	9	15	1
rdma	4	1	1

**Describe the results you expected:**
I'd expect the memory number to remain the same

**Additional information you deem important (e.g. issue happens only occasionally):**
I've tried all combination of the following configurations:
crio - 1.10.5 and 1.11.6
kubelet - 1.10.7 and 1.11.3
cgroup manager: systemd and cgroupfs

All results in the same behavior

**Output of `crio --version`:**

```
crio version 1.11.6
Kubernetes v1.11.3
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
We are running bare metal with centos 7
```
uname -r
4.14.35-1818.2.1.el7uek.x86_64
```
but I've tried it with various kernels as well (el and uek)

**Comment by cyphar** [comment]
That number is the *number* of cgroups on the system -- it doesn't have anything to do with memory usage (other than the couple of bytes in memory that the kernel needs to represent the cgroups). Why is it 2? I'm not sure, but I'm sure that a quick look inside `/proc/self/cgroup` inside a container would probably tell you whether 2 cgroups are being created for each pod (I think that there's a pod-level cgroup and then a container-level one below it).

**Comment by aalubin** [comment]
So only one is created, but my guess goes for the pause container for creating one as well

**Comment by rhatdan** [comment]
@aalubin @mrunalp Is this still an issue?

**Comment by aalubin** [comment]
@rhatdan we no longer use cri-o so I don't know
