### ISSUE TITLE
containerd-release moved, install.tools target broken

### ISSUE THREAD

**Issue by thequailman** [kubernetes-sigs/cri-o#1862]
**Description**

In https://github.com/containerd/containerd/pull/2735, the containerd-release tool was move to a different repo (containerd/project).  The current build process for cri-o is now broken:

```
if [ ! -x "/opt/cri-o/_output/bin/containerd-release" ]; then \
        go get -u github.com/containerd/containerd/cmd/containerd-release; \
fi
package github.com/containerd/containerd/cmd/containerd-release: cannot find package "github.com/containerd/containerd/cmd/containerd-release" in any of:
        /usr/share/go/src/github.com/containerd/containerd/cmd/containerd-release (from $GOROOT)
        /opt/cri-o/_output/src/github.com/containerd/containerd/cmd/containerd-release (from $GOPATH)
Makefile:224: recipe for target '.install.release' failed
make: *** [.install.release] Error 1
```

**Steps to reproduce the issue:**
1.  Checkout cri-o
2.  Run `make install.tools`

**Describe the results you received:**

Unable to build `install.tools` target

**Describe the results you expected:**

Build `install.tools` target

**Additional information you deem important (e.g. issue happens only occasionally):**

I was able to fix this by:
`go get -u github.com/containerd/project/cmd/release-tool`
`mv /root/go/bin/release-tool /opt/cri-o/_output/bin/containerd-release`

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Debian 9

**Comment by mrunalp** [comment]
This is fixed with #1865. Closing. Feel free to reopen if you still see it. Thanks!
