### ISSUE TITLE
Bind mount for /dev not handled correctly

### ISSUE THREAD

**Issue by amshinde** [kubernetes-sigs/cri-o#1881]
After passing host /dev as a volume to a container, I was seeing issues accessing certain devices within the container. Inspecting the config.json for the container, revealed that two mounts had been added with destination /dev.
```
 {
                        "destination": "/dev",
                        "type": "tmpfs",
                        "source": "tmpfs",
                        "options": [
                                "nosuid",
                                "strictatime",
                                "mode=755",
                                "size=65536k"
                        ]
},
...
 {
                        "destination": "/dev",
                        "type": "bind",
                        "source": "/dev",
                        "options": [
                                "rw",
                                "rbind",
                                "nodev",
                                "rprivate",
                                "bind"
                        ]
},
```
Shouldn't the config.json just contain the second bind mount?

**Comment by amshinde** [comment]
cc @mythi 
cc @mrunalp

**Comment by amshinde** [comment]
Took a brief look at how the mounts are added to the spec:
https://github.com/kubernetes-sigs/cri-o/blob/master/server/container_create_linux.go#L844

I think its necessary to override the mount created by the spec generator by user supplied mount.
In case of /dev,  I think it is necessary to filter out all the mounts under /dev that have been created by spec generator.

**Comment by jnummelin** [comment]
We're getting hit by this too with Rook&Ceph:
```
2018-11-01 07:16:15.909661 I | rook-discover: failed to probe devices: failed initial hardware discovery. failed to list all devices: Failed to complete 'lsblk all': open /dev/null: permission denied. 
2018-11-01 07:16:15.909738 I | rook-discover: failed to update device configmap: failed initial hardware discovery. failed to list all devices: Failed to complete 'lsblk all': open /dev/null: permission denied. 
failed initial hardware discovery. failed to list all devices: Failed to complete 'lsblk all': open /dev/null: permission denied.
```

Affects versions >= 1.11.7, 1.11.6 works fine.

My guess it's cause of this: https://github.com/kubernetes-sigs/cri-o/pull/1831

**Comment by mythi** [comment]
> Affects versions >= 1.11.7, 1.11.6 works fine.

our issue is seen with 1.11.6 too.

**Comment by mrunalp** [comment]
Looks like must be because of `nodev`. We will fix and add a test so we don't regress on this. Thanks!

**Comment by mythi** [comment]
@runcom @amshinde the bug I saw (I worked with @amshinde) is at least gone.

```
crio version 1.11.9-dev
commit: "c22b5ef27271152006998e8345414b208dc16a62"
```

**Comment by runcom** [comment]
awesome, that has been fixed by #1884 when I backported that fix to 1.11 and 1.12, we're going to release new tags hopefully by end of the week. Thanks a lot for checking.

**Comment by amshinde** [comment]
cc @lsm5

**Comment by mythi** [comment]
@amshinde Make sure you have https://github.com/kubernetes-sigs/cri-o/releases/tag/v1.12.1.
