### ISSUE TITLE
Make container log path configurable

### ISSUE THREAD

**Issue by jareksm** [kubernetes-sigs/cri-o#1894]
I'm using filebeat from ElasticSearch to collect containers logs. It can discover and read CRIO log format in kubernetes as long as it's in /var/lib/docker/containers/{container id}/&ast;.log. The issue is after moving from docker to crio as the runtime for our cluster the logs are written to /var/log/pods/{pod uid}/{container name}/&ast;.log. After looking at code base, it looks like crio gets the location for writing logs from kubelet. Is there a way to over ride this? For example use another path which uses container ids instead of pod uids/container names?

**Comment by runcom** [comment]
that's more of a question for kubernetes itself - CRI-O just does whatever Kube tells it to do

**Comment by jareksm** [comment]
That's what I've figured out in above, I was hoping for some hints/pointers into getting Kube to tell CRIO a new container log path.

**Comment by runcom** [comment]
I believe there's no such a knob unfortunately :(

**Comment by jareksm** [comment]
This issue has been addressed in filebeat which is referenced in this ticket, as such I'm closing it.
