### ISSUE TITLE
#BUG#Kata runtime was not connected with network namespace

### ISSUE THREAD

**Issue by clarklee92** [kubernetes-sigs/cri-o#1896]
**Description**

**Steps to reproduce the issue:**
1.Using CRI-O 1.11.7 with kata untrusted pod on CentOS7; 
2.CNI conf:
{
    "cniVersion": "0.3.0",
    "name": "kubenet",
    "type": "bridge",
    "bridge": "cbr0",
    "mtu": 1400,
    "addIf": "eth0",
    "isGateway": true,
    "ipMasq": false,
    "hairpinMode": false,
    "ipam": {
        "type": "host-local",
        "subnet": "172.19.1.0/24",
        "gateway": "172.19.1.1",
        "routes": [
            { "dst": "0.0.0.0/0" }
        ]
    }
}
{
  "cniVersion": "0.3.0",
  "name": "kubenet-loopback",
  "type": "loopback"
}
3.The Pod bridge cbr0 was arranged corrected IP address and network is flat. 

**Describe the results you received:**
But kata Pod was found no eth0 and there is no kata_tap in it's network namespace.

**Describe the results you expected:**
I thought there maybe one step missing, I found no relevant error log in `journalctl -u crio.service`. The same ENV I tried with CRI-Containerd and It's ok.
Many thanks.
Sincerely yours

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
1.11.7
```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by runcom** [comment]
@sboeuf @chavafg PTAL

**Comment by mrunalp** [comment]
Can you share your crio.conf?
Also check if you have `manage_network_ns_lifecycle` set to true in it. Thanks!

**Comment by clarklee92** [comment]
> Can you share your crio.conf?
> Also check if you have `manage_network_ns_lifecycle` set to true in it. Thanks!

Thank you very much!! problem was solved. Cause I did's see any conf describe from /kubernetes-sigs/cri-o/docs, I didn't know there is a extra configuration when using kata. This `manage_network_ns_lifecycle` only appears at kata's wiki.
Thank you again!

**Comment by runcom** [comment]
Closing this, feel free to enhance docs if we need to :)
