### ISSUE TITLE
Inconsistent SELinux context for privileged pods

### ISSUE THREAD

**Issue by squeed** [kubernetes-sigs/cri-o#1904]
**Description**
I witnessed inconsistent SELinux contexts for the exact same pod definition. Deleting and re-creating the pod would cause it to have one of `container_t` or `spc_t` without changing the PodSpec at all.

This only occurred for pods with both `privileged: true` and `runAsUser: 0`, e.g.

```yaml
spec:
  containers:
  - name: foo
    securityContext:
      privileged: true
      runAsUser: 0
```

This configuration has worked consistently with Docker-based systems.

**Steps to reproduce the issue:**
1. Create a pod with the above `securityContext`
2. Look to see the process' context (e.g. with ps --context -aux)
3. Delete and re-create the *whole pod* (not the container).
4. Check the context again.

**Describe the results you received:**
The pod first has `container_t`, later `spc_t`

**Describe the results you expected:**
The pod always has `spc_t`

**Additional information you deem important (e.g. issue happens only occasionally):**
The issue is fairly reliably reproducible, but not always. It seems to only happen for "fresh"  nodes joining an existing OpenShift cluster.

The issue never occurs if `runAsUser` is not specified.

**Output of `crio --version`:**
```
[root@test1-bootstrap core]# crio --version
crio version 1.11.8
[root@test1-bootstrap core]# cat /etc/os-release 
NAME="Red Hat CoreOS"
VERSION="4.0"
OSTREE_VERSION=47.71
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
libvirt/qemu, as created by the openshift installer, on RHCOS.

**Comment by runcom** [comment]
Thanks, I'm taking a look at it in a while

**Comment by rhatdan** [comment]
A privileged container should run as spc_t, not as container_t, if you switch a container from non privileged to privileged this could happen?

**Comment by squeed** [comment]
@rhatdan The container's configuration isn't changing, AFAICT.

Since removing `runAsUser: 0` this hasn't happened.

**Comment by rhatdan** [comment]
Ok so that means the CRI-O was treating runAsUser:0 differently then when it was not speicified in such a way that at least the `privileged` flag for SELinux was being ignored.  I am wondering if it `privileged` is ignored altogether.

@umohnani8 PTAL

**Comment by rhatdan** [comment]
I am wondering if runUser:0 causes all capabilities to be removed as well?  Is it only checking if a runuser was specified, then tighten the security.  IE does CRI-O see runUser being set as an indicator that this means run without root privs.  Where it should be combination of runUser being set and the user not being == 0.

**Comment by runcom** [comment]
when getting RunAsUser from Kube in CRI-O we don't deal with privileged or capabilities at all, we just set the user id of runc which shouldn't cause anything like this or privileged to be ignored. I'll check again

**Comment by runcom** [comment]
FYI, I'm trying to recreate the issue with an openshift/installer cluster

**Comment by giuseppe** [comment]
could you help me to find a better reproducer?

I've installer a local libvirt cluster (using version 2507518e40cb851d7b38e5463aadd9d9293fe91b of the installer):

```
$ cat /etc/os-release 
NAME="Red Hat CoreOS"
VERSION="4.0"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION_ID="4.0"
PRETTY_NAME="Red Hat CoreOS 4.0"
ANSI_COLOR="0;31"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat 7"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.0"
REDHAT_SUPPORT_PRODUCT="Red Hat"
REDHAT_SUPPORT_PRODUCT_VERSION="4.0"
OSTREE_VERSION=47.106
```

I've created/deleted a bunch of pods with (and slight modifications of):

```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: busybox
    command: ["sleep"]
    args: ["100000"]
    securityContext:
      privileged: true
      runAsUser: 0
```

but I always get:

```
system_u:system_r:spc_t:s0      root     28931  0.0  0.0   1224     4 ?        Ss   09:15   0:00 sleep 100000
```

**Comment by runcom** [comment]
There's a conversatoin I had with @squeed on Slack, I'll ping you there!

**Comment by squeed** [comment]
Hmm! I can think of a only a few differences between my particular situation and the reproducer:

1 - It only seemed to happen very early on in the node's life
2- It was hostNetwork
3- It bind-mounted a lot of stuff, including `/var/run`
4- It used a rhel base image

I don't think 4 is really meaningful, but number 1 is, I think, more interesting. So I'd suggest doing this:

- Changing the reproducer to a DaemonSet with `hostNetwork: true`
- Using the machine API to rapidly create and destroy many VMs (see below)

This will cause the pod to be created and the daemonset to run very early. Hopefully that makes it easier to reproduce.


To create and delete VMs, do
```sh
kubectl -n openshift-cluster-api edit machineset test1-worker-0
```
and set `replicas:1` to a new number. Within 30 seconds, machines will be created or deleted. You can also set the VM to use only 1024 MiB of ram, so you can create more of them at a time. I would just change replicas from 0 to 2, back and forth, to reproduce.

**Comment by giuseppe** [comment]
I've been trying to reproduce this issue (with the reproducer you provided me) for several days now, but I wasn't able to see it happening even once.  I've switched back and forth from 0 to 2 replicas for the worker nodes.

Are you still observing it with latest images?

**Comment by giuseppe** [comment]
no updates since last November, so closing the issue, please re-open if it still happens
