### ISSUE TITLE
Cross Compilation

### ISSUE THREAD

**Issue by knusbaum** [kubernetes-sigs/cri-o#1932]
**Description**

Cross Compilation appears not to work.

**Steps to reproduce the issue:**
1. Run `make install.tools`
2. Set `GOARCH` to a target platform not the same as the host.
3. Run `make`

**Describe the results you received:**
Compilation encounters error.
```
/bin/sh: /builddir/cri-o-1.12.1/bin/crio-config: cannot execute binary file: Exec format error
```

**Describe the results you expected:**
Compilation should succeed

I expect that the `crio-config` should be built as part of the install tools rather than as part of the main compilation.

If I move `crio-config` to be built as part of install.tools, I get the following error when running make:
```
/bin/sh: ./bin/crio: cannot execute binary file: Exec format error
```

**Comment by rhatdan** [comment]
The PR is closed.  Closing.
