### ISSUE TITLE
Default Crio install should support any registry.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cri-o#1970]
It seems like the default CRIO installation on minikube, for example, might benefit from not needing people to modify the `/etc/crio/crio.conf` file to have default registries.

**Comment by jayunit100** [comment]
Workaround: For me, after launching `minikube start` with crio options, I `minikube ssh` and manually update the configuration file above, to , for example, reference `docker.io`, i.e. 

```
registries = [
"docker.io", "gcr.io"
]
```

Not sure if we can just default those registries on install or add it as a minikube run option.

**Comment by rhatdan** [comment]
I don't see this as a CRI-O issue. Reopen if you disagree.
