### ISSUE TITLE
Consider switching to go mod

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/cri-o#1972]
With go 1.11 we have the option to use native [golang modules](https://github.com/golang/go/wiki/Modules), which can be explicitly enabled and disabled during build.

It would like to create a PR to switch to go modules. What is your opinion on this?

**Comment by runcom** [comment]
where do you see the need to modularize CRI-O though? I would be ok with this but want to know what/where/which we're going to use a module for

**Comment by saschagrunert** [comment]
The main intention of mine is to have a better update-ability of the used vendored packages. For example, if I want to update a package it would be a bit tricky if the package structure changed over time since we only vendor necessary go files right? I guess this would be solved with `go mod` since it also vendors only _used_ packages.

**Comment by runcom** [comment]
it would be awesome, thanks!!!

**Comment by saschagrunert** [comment]
Alright, I created some playground branch here: https://github.com/openSUSE/cri-o/tree/go-mod
and found a more or less game breaking issue:

- go mod is now taking case sensitivity into account, which means there are packages which use `github.com/sirupsen/logrus` and `github.com/Sirupsen/logrus`. This leads into breaking the build.

**Comment by runcom** [comment]
> The line `replace github.com/Sirupsen/logrus v1.2.0 => github.com/sirupsen/logrus v1.0.0` in `go.mod` does also not solve the problem, because this does not modify any code at all.

isn't there any tool to fix it? like go mod tidy or gohack or https://github.com/marwan-at-work/mod

**Comment by vrothberg** [comment]
I'd prefer to wait until modules are considered stable. Vendoring isn't perfect but it currently works :^)

**Comment by runcom** [comment]
this is meant as a way to help upstream catch bugs early, not to go with this right now :)

**Comment by saschagrunert** [comment]
Yeah I agree, a somewhat hacking test from my side was:

The _find it out yourself_ appraoch:
```fish
> set -x GO111MODULE on
> rm -rf vendor vendor.conf
> go mod init
go: creating new go.mod: module github.com/kubernetes-sigs/cri-o
> echo "replace github.com/Sirupsen/logrus v1.2.0 => github.com/sirupsen/logrus v1.2.0" >> go.mod
> go mod vendor
...
> make
go build -i -ldflags '-s -w -X main.gitCommit="eb97f2acf3a173bc173c37d3c149935c26a5394f-dirty" -X main.buildInfo=1545149418' -tags "     seccomp selinux  containers_image_ostree_stub" -o bin/crio github.com/kubernetes-sigs/cri-o/cmd/crio
go: finding k8s.io/kubernetes/pkg/util/term latest
go: finding k8s.io/kubernetes/pkg/util latest
go: finding k8s.io/kubernetes/pkg latest
go: github.com/sirupsen/logrus@v1.2.0 used for two different module paths (github.com/Sirupsen/logrus and github.com/sirupsen/logrus)
make: *** [Makefile:103: bin/crio] Error 1
> sed -i 's/Sirupsen/sirupsen/g' **.go
> make
...
go: github.com/sirupsen/logrus@v1.2.0 used for two different module paths (github.com/Sirupsen/logrus and github.com/sirupsen/logrus)
make: *** [Makefile:103: bin/crio] Error 1
```
So no luck with that, without further hacking around.

The _convert it please_ approach:
```fish
> set -x GO111MODULE on
> go mod init
go: creating new go.mod: module github.com/kubernetes-sigs/cri-o
go: copying requirements from vendor.conf
> go mod vendor
...
go: github.com/Sirupsen/logrus@v1.2.0: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"
go: error loading module requirements
> echo "replace github.com/Sirupsen/logrus v1.2.0 => github.com/sirupsen/logrus v1.2.0" >> go.mod
> go mod vendor
...
> make
../../../../pkg/mod/github.com/docker/docker@v1.13.1/pkg/fileutils/fileutils.go:13:2: case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"
oci/oci_unix.go:17:2: unknown import path "k8s.io/kubernetes/pkg/util/term": cannot find module providing package k8s.io/kubernetes/pkg/util/term
make: *** [Makefile:103: bin/crio] Error 1
```
Also further modifications of the go.mod and sedding around brings me currently not to the target.

I guess since the dependency tree is messed up with [Ss]irupsen paths everything else fells hacky.

**Comment by saschagrunert** [comment]
I guess https://github.com/kubernetes/kubernetes/issues/63607 and https://github.com/kubernetes/kubernetes/issues/68577 are related.

**Comment by cyphar** [comment]
>  but in the end that means we are on the latest master for the first level of module dependencies. 

Whoa, you don't need to check out `master` -- you can check out a specific version of your module dependencies by doing `go get -u thing@<version>`. Absolutely without question it's a bad idea to use `latest` for everything.

In addition, `go mod` has a conversion tool that will take many existing vendoring manifests and translate them to `vendor.conf`. So you could just do that, and keep the existing dependencies at their currently-pinned versions.

**Comment by cyphar** [comment]
> but in the end that means we are on the latest master for the first level of module dependencies. 

That shouldn't be the case at all -- the `vendor.conf` translation should've stored what commits are pinned there (and the whole `go.mod` thing is supposed to avoid having master checkouts for module dependencies). However, looking at `vendor.conf` it looks like several of our dependencies just point at `master` (I'm not going to get into why this isn't the best idea in the world) -- so you'll need to replace them with the last-checkout commit.

**Comment by rhatdan** [comment]
@saschagrunert Any movement on this issue?

**Comment by saschagrunert** [comment]
@rhatdan Not for now, I will close this issue for now since it seems a long term topic which has to be split in several single issues.
