### ISSUE TITLE
Possible segmentation fault in `prepareReference()`

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/cri-o#1980]
The method `prepareReference()` in `pkg/storage/image.go` is used by multiple other methods within the same file (like `PrepareImage` and `PullImage`).

https://github.com/kubernetes-sigs/cri-o/blob/12ec0b28e3d7b5028c42270480c8d3c72258e377/pkg/storage/image.go#L354-L380

If I call the method with a valid `imageName` which uses another transport as `docker://`, the call to `reference.Domain(srcRef.DockerReference())` on line 375 will cause a nil pointer dereference. This can be verified by a call to 

```go
imageServer.PullImage(&types.SystemContext{}, "oci://test:latest", &copy.Options{})
```

I am not sure if this is a real world issue and wanted to clarify how function should behave when pulling from non-docker transports.

**Comment by runcom** [comment]
Thanks for the report, I've opened #1981
