### ISSUE TITLE
Switch the oci.Runtime structure to a Go interface

### ISSUE THREAD

**Issue by sboeuf** [kubernetes-sigs/cri-o#1989]
Following the high level issue #1945, and now that #1946 has been merged, we need to define the Runtime as an interface so that we can define the current runtime implementation as `v1`. This will allow for new implementations (particularly `v2`) in the future, without breaking the core of CRI-O.

**Comment by runcom** [comment]
:+1: this is indeed the first step towards supporting multiple runtimes, thanks!
