### ISSUE TITLE
Tests for additional products

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/cri-o#2009]
Currently the end-to-end test are running against different Red Hat related products. I'm thinking about adding adding additional distributions in the future. Do you think this could be possible somehow (via an additional bot)? :innocent:

**Comment by mrunalp** [comment]
@saschagrunert It should be possible for the infrastructure to report results from different jenkins instances. Intel helped add kata tests which is running on their infra. More than willing to add support for other distros :) We can discuss in this week's meeting.

**Comment by saschagrunert** [comment]
@mrunalp sounds great, is the meeting public for external users and am I able to join? :)

**Comment by mrunalp** [comment]
I will add the details to our wiki and yes you are able to join :)

**Comment by saschagrunert** [comment]
So as discussed within the weekly meeting I will check if we can fulfill the needed requirements and would come back with a proposal.

**Comment by rhatdan** [comment]
@saschagrunert any progress on this?

**Comment by saschagrunert** [comment]
@rhatdan Yeah I made some progress internally, but I’m still in a negotiation phase of getting all necessary requirements together. I will close this issue for now and keep track on my internal issue tracker. The information that it is generell possible is enough for now, thanks!
