### ISSUE TITLE
Request for updating the new and bug fixed version releases on CentOS.

### ISSUE THREAD

**Issue by clarklee92** [kubernetes-sigs/cri-o#2014]
My team need to deploy `cri-o` for our Cloud Container Engine users and I found there is no new enough [CentOS `rpm`](https://cbs.centos.org/koji/packageinfo?packageID=5695) packages as [Ubuntu `deb`](https://launchpad.net/~projectatomic/+archive/ubuntu/ppa), especially we need bug #1995 fixed.
  Building from source code is not suitable for automated deployment. @rhatdan Could you please help to get that?
  Thanks a lot!

**Comment by rhatdan** [comment]
@lsm5 @mrbobbytables Do we have Centos packages?

**Comment by lsm5** [comment]
@fkluknav ^^

**Comment by hardoverflow** [comment]
We need this too! We cannot use k8s 1.13.x. @fkluknav. Many thanks!

**Comment by hardoverflow** [comment]
Can anyone explain us, what the problem with the build process of cri-o for rhel/centos rpm packages is? How can we support?

**Comment by kfox1111** [comment]
+1. I'd like a repo for centos7 that tracks the kubernetes upstream repo. Their versions release more frequently then openshift does.

**Comment by mrunalp** [comment]
We will get this sorted out and update here by tomorrow. Thanks for the patience!

**Comment by lsm5** [comment]
So, CentOS' build system doesn't seem to have the correct repos setup to host 1.13 packages yet. @fkluknav will check with CentOS Infra people on setting those up. If you're ok with locally generated packages until the CentOS repos are setup, I can put packages up on a public page as a temp fix.

@kfox1111 if you'd rather avoid openshift packages, you can use the crio only repo (1.11 for example): https://cbs.centos.org/repos/paas7-crio-311-candidate/x86_64/os/ . The `311` in there does _not_ mean that it tracks openshift and not kubernetes. cri-o packages are independent of openshift and kubernetes as such. HTH.

**Comment by lsm5** [comment]
I built this on a rhel7 machine https://lsm5.fedorapeople.org/cri-o-1.13/ . Hopefully those should unblock you right away. Let me know how it goes.

**Comment by clarklee92** [comment]
> I built this on a rhel7 machine https://lsm5.fedorapeople.org/cri-o-1.13/ . Hopefully those should unblock you right away. Let me know how it goes.

Thank you very much. But the version is still with bug #1995. After it was fixed(1.11, 1.12 and 1.13), there are two versions released: 1.12.4 and 1.11.11 . could you package either of them to rpm? many thanks!

**Comment by fkluknav** [comment]
Hi,
I am trying to build 1.11.11 in cbs now, fiddling with the changed golang dependencies in CentOS. Other versions will follow.

**Comment by fkluknav** [comment]
https://cbs.centos.org/koji/taskinfo?taskID=680821

**Comment by hardoverflow** [comment]
Hello again,

as long as there are no automatic build process for cri-o rhel packages, the issue should be left open @fkluknav .

**Comment by SimonHoenscheid** [comment]
@hardoverflow Good Point!

**Comment by den-is** [comment]
Hey RedHat, where are our fresh RPMs ? :D
Advertises CRI-O here and there, uses in the latest OpenShift 4+ , while we poor centos users can't easily install latest versions (I aware about compilation and binaries)

**Comment by lsm5** [comment]
sometime next month I hope to have the process in place to rebuild fedora cri-o rpms for CentOS PaaS SIG. If anyone's interested in making this quicker by joining PaaS SIG, let me know :)
