### ISSUE TITLE
Make cri-o socket accessible without root permissions

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/cri-o#2029]
The idea [from an issue in cri-tools](https://github.com/kubernetes-sigs/cri-tools/issues/426) is to run crictl without being root. One first step towards this would be to introduce a dedicated user/group for cri-o and create the socket with that permissions.

**Comment by rhatdan** [comment]
Realize that this opens a HUGE security hole, and should be done very carefully, IE users need to realize if you give access to a socket like this, it is worse then sudo with no password, since logs can be cleaned up and no record of you running a pod/container would be recorded.

**Comment by rhatdan** [comment]
@saschagrunert Why is this needed?  I would prefer to just force the use of sudo crictl.

**Comment by saschagrunert** [comment]
> @saschagrunert Why is this needed? I would prefer to just force the use of sudo crictl.

So if you think this is really not needed then feel free to shut me down and close this issue. I just thought it could be a valuable addition. :upside_down_face:

**Comment by mrunalp** [comment]
@saschagrunert I think the big concern here is potential security issues :)

**Comment by mrunalp** [comment]
Thanks! We can revisit this later if needed. Closing for now.

**Comment by saschagrunert** [comment]
> @saschagrunert CRI-O can be launched in an unprivileged user namespace with `_CRIO_ROOTLESS=1`.
> https://github.com/rootless-containers/usernetes/blob/master/boot/crio.sh

Good to know, thanks for the hint! :)

**Comment by dciancio** [comment]
I've added the following in the crio.service systemd file and works fine.
ExecStartPost=/bin/sh -c 'chmod 0775 /var/run/crio/crio.sock && chgrp docker /var/run/crio/crio.sock'
Note that I also have docker installed and have already configured the docker daemon to be accessed using users in the docker group.
An upgrade to crio will crush changes to the default crio.service systemd file so be sure to configure your changes in a custom file under /etc/systemd/system.

**Comment by koct9i** [comment]
Better solution using ACL:
`ExecStartPost=/bin/setfacl -m g:docker:rw /var/run/crio/crio.sock`
