### ISSUE TITLE
RHCOS 4.0 is missing /usr/share/containers/oci/hooks.d therefore /etc/containers/oci/hooks.d is never read

### ISSUE THREAD

**Issue by zvonkok** [kubernetes-sigs/cri-o#2037]
**Description**

On a OCP4.0 cluster with RHCOS 4.0 installed, the directory `/usr/share/containers/oci/hooks.d` is missing. If this directory is missing cri-o will not read additional hook files from `/etc/containers/oci/hooks.d`. Since `/usr` is read-only I can only place hook files into `/etc/containers/oci/hooks.d` but these are not been executed. 

I have seen this #1942 that ignores the hook dirs (`/etc`) if not existent. Does this fix ignore all provided hook directories if not existent? So if in my example the `/usr` dir is missing it will go and check for the `/etc` hook dir?

Can this be backported to cri-o 1.12? 

**Steps to reproduce the issue:**
1. On a RHCOS 4.0 place a hook into `/etc/containers/oci/hooks.d`
2. Run a container that triggers the hook

**Describe the results you received:**
The hook is not executed because of the missing `/usr/` hook directory. 

**Describe the results you expected:**
CRIO ignores the non existent directory and tries to read the hooks from the next hook directory. 
**Output of `crio --version`:**
```
crio version 1.12.4-4.rhaos4.0.git8ecb249.el7
```

**Comment by baichinger** [comment]
You need to restart CRI-O daemon as those directories get evaluated during startup.

**Comment by zvonkok** [comment]
@baichinger If `/usr/share/containers/oci/hooks.d ` is missing, cri-o will not evaluate `/etc/containers/oci/hooks.d`. My hooks are in `/etc/containers/oci/hooks.d`. 

If I restart cri-o it wll fail to read  `/usr/share/containers/oci/hooks.d ` and will not read additional hooks from `/etc/containers/oci/hooks.d`.

**Comment by mrunalp** [comment]
@QiWang19 can you look into this?

**Comment by aloismayr** [comment]
The fix provided for #1942 is critical for us to properly support OCP 4.0. Any chance to get it merged into a 1.12 release?

**Comment by QiWang19** [comment]
@zvonkok Did you config this path `/etc/containers/oci/hooks.d` to `/etc/crio/crio.conf`

**Comment by mrunalp** [comment]
@QiWang19 Can you backport #1943 to `release-1.12` ?

**Comment by QiWang19** [comment]
@mrunalp sure

**Comment by mrunalp** [comment]
This has been merged and will be available in next builds.

**Comment by rhatdan** [comment]
In current CRI-O
