### ISSUE TITLE
Apparmor integration tests

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/cri-o#2040]
During the port of the integration tests to other distributions I found out that the apparmor related tests (`test/apparmor.bats`) are skipped and not working anymore. Is it intended to enable this later on Fedora and RHEL? I could have a look into this in some time.

**Comment by vrothberg** [comment]
AppArmor is not available there but on Ubuntu/Debian and openSUSE, where the test could/should run.

We were just ironing out some hiccups over at libpod (see https://github.com/containers/libpod/pull/2224) to also make CI test AppArmor there as well. CRI-O is using libpod's AppArmor package.
