### ISSUE TITLE
not starting: "unknown option: .skip_mount_home"

### ISSUE THREAD

**Issue by owetterau** [kubernetes-sigs/cri-o#2056]
On a current OpenSUSE Kubic installation with CRI-O version 1.13.0 crio is suddenly not starting anymore with this error message in the log:

2019-02-06T00:00:07.512292+00:00 kube-master crio[27469]: time="2019-02-06 00:00:07.511695552Z" level=fatal msg="Unknown option .skip_mount_home"

This also happened on another installation also using the latest OpenSUSE Kubic with the same version of crio.

Both errors started appearing at the same date (6th of February). And due to this, Kubernetes is not working anymore.

**Comment by vrothberg** [comment]
This is an openSUSE Kubic bug (Cc @sysrich) which should be fixed with the next snapshot.

**Comment by owetterau** [comment]
Thanks for the quick reply. Any idea when this snapshot will be available?

**Comment by vrothberg** [comment]
> Thanks for the quick reply. Any idea when this snapshot will be available?

@sysrich should know. A quick workaround would be to remove this option from `/etc/containers/storage.conf`.

**Comment by owetterau** [comment]
Unfortunately, removing the option does not work.

**Comment by sysrich** [comment]
@owetterau are you sure? commenting out the line works fine on all of our tests, and on my machines..

the next snapshot should be released some hours from now, it's going through testing as we speak

You can download the under-testing iso from the following link

https://openqa.opensuse.org/tests/847500/asset/iso/openSUSE-Tumbleweed-Kubic-DVD-x86_64-Snapshot20190205-Media.iso

**Comment by owetterau** [comment]
Yes, it does not work. I checked and now there is a different error message: "Unknown option .mountopt".

I checked this on different installations.

**Comment by sysrich** [comment]
@owetterau ok, not entirely sure how you ended up with .mountopt set.. but looking at my reference machines here both `mountopt=` and `skip_mount_home=` should be commented out in `/etc/containers/storage.conf` - that should get you back up and running without needing the new snapshot

and I can confirm both are commented out correctly in the in-testing snapshot

**Comment by owetterau** [comment]
@sysrich Commenting out both options works fine! So, we are good for now.
I will check if the next snapshot also works.

Many thanks for the quick help! 👍

**Comment by sysrich** [comment]
@owetterau sorry for the problem - our testing and release processes are being tuned up to make sure it can't happen again (the automation worked pretty well..humans sadly are still fallible ;))
