### ISSUE TITLE
Vendor libpod

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/cri-o#2063]
Some changes and fixes related to libpod are needed within cri-o too (like https://github.com/containers/libpod/pull/2114). The plan would be to vendor libpod v1.0.0 in, but for the mentioned fix this would not be enough.

Are there any plans on your side to switch cri-o to libpod (like re-using `libpod/container.go`)?

I would't have the time in the next weeks to do this so I would like to ask you if this topic fits in your latest plans? If you say that this is not your top priority right now I would be able to look into that topic too after my time-off (mid of march).

**Comment by mrunalp** [comment]
We do eventually want to do that but ensuring that we don't regress on any performance. Over the last year we changes to crio to improve the perf and we want to ensure that we don't regress on it.

**Comment by rhatdan** [comment]
Continue to plan to do this.

**Comment by saschagrunert** [comment]
I think I can look into this issue in some days.
