### ISSUE TITLE
pkg/storage/runtime_test.go is mostly wrong

### ISSUE THREAD

**Issue by mtrmac** [kubernetes-sigs/cri-o#2117]
**Description**

The tests in pkg/storage/runtime_test.go use `imageName` as a name of an image to be pulled. Because uppercase letters are invalid in Docker references (and therefore also `containers-storage:` references), the test exercise code paths that don’t match the real world much.

**Steps to reproduce the issue:**
1. `s/imageName/imagename/g` in `pkg/storage/runtime_test.go`
2. `go test ./pkg/storage`

**Describe the results you received:**

15 failures

**Describe the results you expected:**

Tests succeeding, same as after `s/imageName/imageName2/g` in the file.

**Output of `crio --version`:**

HEAD as of commit a226a57727a7d88aa6ab9f958317003abd4d86fd .

**Comment by saschagrunert** [comment]
Hey @mtrmac thank you for reporting the issue. I prepared a fix for it in #2132 and you may want to have a look into that. :)

**Comment by mtrmac** [comment]
Thanks! That PR is a big improvement.

I’ve noted a few concerns in there (but the GoMock expectations are honestly incomprehensible to me stand-alone, so I might well have missed something), but now that the main paths are represented accurately, that’s much less important.

**Comment by saschagrunert** [comment]
Thank you for the review! I will check if I can improve the mocking further…
