### ISSUE TITLE
[Documentation] What is the meaning of `Cefs` in  `Support for network based file system images (NFS, Gluster, Cefs)`?

### ISSUE THREAD

**Issue by pando85** [kubernetes-sigs/cri-o#2125]
Hi, in [website](https://cri-o.io/#storage) it is written that  `Support for network based file system images (NFS, Gluster, Cefs)`. What is the meaning of `Cefs` in that context?

Could be [Ceph FS](http://docs.ceph.com/docs/master/cephfs/)?
Thanks.

**Comment by mrunalp** [comment]
Yes, it is Ceph FS. You can open a PR here to get it fixed - https://github.com/cri-o/cri-o.io

**Comment by pando85** [comment]
Thanks @mrunalp.
I made [it](https://github.com/cri-o/cri-o.io/pull/27) but I don't know if this information is outdated. I saw [this PR](https://github.com/containers/storage/pull/50) and I don't find more information about current state of this feature.

**Comment by haircommander** [comment]
closing per https://github.com/cri-o/cri-o.io/pull/27
