### ISSUE TITLE
Networking namespaces are explicitly removed

### ISSUE THREAD

**Issue by sameo** [kubernetes-sigs/cri-o#278]
CNI will not set the netns mounted flag when getting an existing networking namespace.
This forces us into tracking netns states and removing them explicitly depending on their state, instead of just calling `ns.Close`. This is merged through PR #276.

There is a pending PR for CNI that attempt to fix that issue: https://github.com/containernetworking/cni/pull/342
If it gets merged, we should revert PR #276.

**Comment by rhatdan** [comment]
@sameo what should we do with this issue?

**Comment by rhatdan** [comment]
@sameo @runcom @mrunalp Is this fixed?

**Comment by rhatdan** [comment]
Since this is several year old and no one responds to me, I am going to assume it is fixed.  Reopen if I am wrong.
