### ISSUE TITLE
Add optional journal logging option

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-sigs/cri-o#377]
We need to add a journald option to conmon similar to the docker journald plugin. journald provides the following features that are useful in production: 

- rate limiting
- log rotation
- systemd tooling integration

**Comment by cyphar** [comment]
:/ It begins. Is there no way we can do it without adding logging plugins to `conmon`?

**Comment by runcom** [comment]
> :/ It begins. Is there no way we can do it without adding logging plugins to conmon?

well, we could just go and implement everything in conmon of couse ha - or just take advantage of what distros (like RH, SUSE) offer when it comes to logging and all the heavy stuff that comes with it. 
@cyphar something like this would probably be needed anyway, I believe @mrunalp added it just for tracking purpose, nothing actionable immediately till we pass k8s tests.

**Comment by rhatdan** [comment]
I think this is something we should look at post 1.0.

**Comment by wking** [comment]
Can't we get this (for unstructured logs) with [journald's stream logging][1] while `conmon` continues to log to stderr?

[1]: https://www.freedesktop.org/software/systemd/man/systemd-journald.service.html

**Comment by rhatdan** [comment]
Looks like this is making progress.

**Comment by haircommander** [comment]
closing per #2086 landing :D
