### ISSUE TITLE
Add BAT tests for exec

### ISSUE THREAD

**Issue by sameo** [kubernetes-sigs/cri-o#477]
Now that we support CRI's `exec`, we should add functional tests for it.

**Comment by sameo** [comment]
@runcom @mrunalp Please feel free to assign that one to me.

**Comment by rhatdan** [comment]
@sameo Is this still a problem?

**Comment by rhatdan** [comment]
@sameo @runcom @mrunalp Do we have tests for this now?  Can I close this?

**Comment by umohnani8** [comment]
We have both unit and BAT tests for exec. @mrunalp @rhatdan I think this can be closed.
