### ISSUE TITLE
Add BAT tests for port forwarding

### ISSUE THREAD

**Issue by sameo** [kubernetes-sigs/cri-o#478]
Now that we support port forwarding, we should add functional tests for it.

**Comment by sameo** [comment]
@runcom @mrunalp Please feel free to assign that one to me.

**Comment by mrunalp** [comment]
@sameo Thanks!

**Comment by rhatdan** [comment]
@sameo did you complete this?

**Comment by rhatdan** [comment]
@sameo @runcom @mrunalp Do we have tests for this now?

**Comment by rhatdan** [comment]
Since this was never answered and a year old, I am going to close.
