### ISSUE TITLE
rate limit logging in conmon

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-sigs/cri-o#483]
We should rate limit logging in conmon to limit I/O usage.

**Comment by smarterclayton** [comment]
Both back pressure and dropping need to be eventually supported.  Backpressure is more useful today.

**Comment by mrunalp** [comment]
@smarterclayton Do we want to do our own throttling or just rely on cgroups?

**Comment by smarterclayton** [comment]
our own eventually.  for dropping I'd expect a ring buffer and for that I'd expect a fixed size to be configurable, potentially per pod at some point.  The log options on the docker engine are reasonably close to what I'd expect today at a high level (a good model).

**Comment by rhatdan** [comment]
@mrunalp Any update on this issue?

**Comment by rhatdan** [comment]
Since this has not been touched in over a year.  I am going to close.  It does not seem to be an issue now.  Reopen if you disagree.
