### ISSUE TITLE
[RFC] Fix firewalld and dockerd iptables when running e2e tests

### ISSUE THREAD

**Issue by sameo** [kubernetes-sigs/cri-o#484]
Both `firewalld` and `dockerd` set some fairly restrictive iptables rules that prevent `ocid` from passing the e2e tests. 

We may want to add a `-iptables-fix` option for overwriting those rules if/when they exist (and restore them when ocid terminates). By default `ocid` would not mess with iptables at all.

**Comment by sameo** [comment]
cc @mrunalp @rhatdan @runcom

**Comment by mrunalp** [comment]
Can we use firewalld/iptables to fix those rules for the duration of the test?

**Comment by rhatdan** [comment]
@sameo is this still an issue?

**Comment by mrunalp** [comment]
Yeah, this is an issue. ping @rajatchopra @dcbw

**Comment by rhatdan** [comment]
@mrunalp @rajatchopra @dcbw is this still an issue?

**Comment by mrunalp** [comment]
This is fixed.
