### ISSUE TITLE
Split bind and advertise adress

### ISSUE THREAD

**Issue by runcom** [kubernetes-sigs/cri-o#594]
ref: https://github.com/kubernetes-incubator/cri-o/pull/590

we need a way to split those addresses for the streaming server

@mrunalp @sameo @apilloud

**Comment by apilloud** [comment]
To add more context: The server might want to bind to the wildcard address and advertise a public address, possibly one that isn't on the host. (An AWS public IP for example.)

**Comment by mrunalp** [comment]
@apilloud Is this something you can work on?

**Comment by rhatdan** [comment]
@apilloud ?

**Comment by apilloud** [comment]
Sorry I didn't comment here. Took a look at this, it doesn't really seem useful to me without something like the cloud provider API to discover the public address. I don't have time to work on it at the moment.

**Comment by m1093782566** [comment]
Hi all,

Can I work on it?

**Comment by rhatdan** [comment]
@m1093782566 Did you ever work on this?  Anyone?

**Comment by m1093782566** [comment]
NO

**Comment by rhatdan** [comment]
@runcom Is this still something we care about?  Do we have a trello card for it?

**Comment by rhatdan** [comment]
Well another year has gone by and no movement on this.  I will close.  Reopen if this is still important.
