### ISSUE TITLE
Reduce event spam

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-sigs/cri-o#600]
We want to add code and test this in cri-o as well 
https://github.com/kubernetes/kubernetes/pull/47462/files

@derekwaynecarr

**Comment by runcom** [comment]
we don't really control how CRI-O handles errors to kube - kuberuntime should do the lift and cleanup from "rpc error code blablabla" I guess (if I have understood correctly the issue, otherwise sorry for the noise)

**Comment by rhatdan** [comment]
@mrunalp Did you ever do this?

**Comment by rhatdan** [comment]
@runcom @mrunalp Did we ever do anything for this?  Can I close this issue?
