### ISSUE TITLE
#cri-o on kubernetes.slack.com

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-sigs/cri-o#610]
It will be good to have a slack channel for cri-o in the kubernetes organization.
@sarahnovotny @yujuhong @vishh Could you help with that?

**Comment by amitkumarj441** [comment]
@mrunalp :+1:

**Comment by rhatdan** [comment]
What's the skoop on this, do we still want slack, do we have slack?

**Comment by umohnani8** [comment]
We have the channel, @mrunalp @rhatdan please close this.

**Comment by rhatdan** [comment]
@umohnani8 I can't at this point.  I need to become admin of this repo.
