### ISSUE TITLE
Is the pause container necessary?

### ISSUE THREAD

**Issue by cyphar** [kubernetes-sigs/cri-o#91]
Currently we set up the pause container as k8s already does with Docker. However, it should be noted that (to my understanding) the only purpose of the pause container is to allow for k8s to mess around with the network setup of containers -- since we're using CNI natively it should be possible to not have this requirement.

Or is the pause container a requirement because we need to have some process inside the container as the stem cell for the pod, so we can attach additional containers to the pod? If so, we have to make sure that we **do not** automatically download the pause container from the internet (at SUSE we've had to dive deep into k8s to make sure that we can package all of the components explicitly). From my reading of the code, we don't do that at the moment though.

**Comment by runcom** [comment]
@cyphar to my understand we need to have that process which is holding namespaces and stuff so we can attach other containers. Now we have hacked a solution with the "pause" container but ideally anything can be run as the pod process (systemd?). That said, we still need at least #8 to land before talking about removing that hacked solution.

**Comment by runcom** [comment]
@mrunalp knows better than me about that though so I'll defer a more valid answer to him.

**Comment by mrunalp** [comment]
@cyphar We do not technically need the pause container till there is support for sharing pid namespaces between the containers. We did it this way as it was easiest to get going. 
I am thinking that in the short term, we can provide a simple C based pause container that gets compiled and installed with the other binaries in cri-o.
The real longer term fix is to detect whether pid namespace sharing is configured or not and act accordingly. If pod is going to share pid namespaces then we launch a user configurable init container else just create bind mounted namespaces to represent a pod.

**Comment by resouer** [comment]
Out of curiosity, how can we share network namespace if there's no infra container? 

btw, runv does not need that since hypervisor serves as sandbox naturally.

**Comment by cyphar** [comment]
@resouer It should be possible to do by doing `unshare(CLONE_NEWNET)` and then opening `/proc/self/ns/net` and passing that fd to another process. When the process which called `unshare` dies I don't think that the network namespace will be cleaned up if a process has the file descriptor open.

To be fair, it's not very pretty but I was just wondering if we really needed the pause container (Docker needs it because of the design which is not a limitation of runC).

**Comment by rhatdan** [comment]
I think we should get rid of the pause container.   The problem with docker is they would never accept a patch for something like --net host:/PATHTONETWORKNAMESPACE, then we could get to a primary container running inside of a POD and allow other containers to join that container.

**Comment by laijs** [comment]
I don't like the pause container either, but I can't figure how to handle the pid ns if there is no pause container(when to create the pidns? which process will be the pidns-init-process? how to preserve the pidns for any feature container if all the containers exited)

**Comment by cyphar** [comment]
@laijs You can bindmount namespaces to create "persistent namespaces":

```
% touch /tmp/pidns
% mount --bind /proc/self/ns/pid /tmp/pidns
% ls -la /tmp/pidns
-r--r--r-- 1 root root 0 Dec 16 22:59 /tmp/pidns
```

You can then use `setns(2)` or just pass the path to the runtime configuration and you don't need to have a process in the namespace.

**Comment by cyphar** [comment]
The really weird part is that you also don't need to have ever have been `init` inside the `pidns`! Because `unshare(CLONE_NEWPID)` sets that your children will start inside the new pid namespace, you can bindmount it and exit and the first process to do `setns(the persistent namespace)` will be init!

**Comment by sameo** [comment]
@laijs @cyphar If we're not on the host network namespace, we now create persistent networking namespaces per pod under `/var/run/netns/`. We no longer use the pause pid ns.
If we're on the host network, then we already have a networking namespace.
So having the pause container just to hold the networking namespace no longer makes sense.

Unless someone is already busy with that, I can have a look early next week at completely removing it.

**Comment by cyphar** [comment]
@sameo I'm not working on it right now. But please do remove it if you have time to do that -- the pause container was always one of those hacks I _really_ didn't like. :P

**Comment by mrunalp** [comment]
@sameo I think we just need to apply the same treatment for ipc that you did for net namespace and we should be good. However, having said that we will still need to keep the option of having a "init" container when kubernetes starts supporting sharing pid ns so that init container can act as the reaper for the other containers.

**Comment by laijs** [comment]
> you can bindmount it and exit and the first process to do setns(the persistent namespace) will be init

> how to preserve the pidns for any later container if all previous the containers exited?

```
[root@sbox ~]# unshare -p -f mount --bind /proc/self/ns/pid /tmp/pidns
[root@sbox ~]# nsenter --pid=/tmp/pidns ls
nsenter: fork failed: Cannot allocate memory
```

@cyphar 
it seems any later process can't enter to the pidns if the init process of the pidns had exited.

**Comment by philips** [comment]
You have to have a PID1 to keep the PID namespace open. http://man7.org/linux/man-pages/man7/pid_namespaces.7.html


       If the "init" process of a PID namespace terminates, the kernel
       terminates all of the processes in the namespace via a SIGKILL
       signal.  

To get rid of pause you need a PID1 tied to the lifecycle of the sandbox. This is what we do with rkt. To emulate the old "k8s" behavior we will have [rkt + runc](https://coreos.com/blog/rkt-and-kubernetes.html) put every container in the pod under its own PID ns.

**Comment by mrunalp** [comment]
@philips We plan to support a custom init container when pid ns is shared.

**Comment by cyphar** [comment]
https://github.com/cyphar/initrs is a very minimal init that I've written (in Rust) that handles this job just fine.

**Comment by rhatdan** [comment]
Any update on this issue?

**Comment by wking** [comment]
> Any update on this issue?

#1265 is my first step towards making the pause container optional.  I'd like to leave this open until we have removed the pause-container requirement.

**Comment by RahulG115** [comment]
how can i get /pause container id from master node as it is created in one of slave node ?
is there any  command to do that

**Comment by mrunalp** [comment]
We are going to close this as with the introduction of pid namespaces, the pause/init container is required. If someone is really motivated, they can add a code path to do all the work that we do for non-pid namespace sharing pods but I don't see a big benefit right now. Feel free to re-open if there is interest in reviving this :)

**Comment by AbdouTlili** [comment]
@wking is the pause container no longer a requirement ??

**Comment by haircommander** [comment]
hey @AbdouTlili in some situations, the pause container is no longer a requirement. with the option `drop_infra_ctr = true` cri-o drops the pause container whenever it can. however, it will be a while before the pause container goes away completely, as i'ts currently needed to hold open PID namespaces
