### ISSUE TITLE
set terminal process group (-1): Inappropriate ioctl for device

### ISSUE THREAD

**Issue by runcom** [kubernetes-sigs/cri-o#918]
Running Origin tests with CRI-O, we get the following in one test:
```
Sep 18 06:30:59.726: INFO: At 2017-09-18 06:30:51 -0400 EDT - event for mysql-1-2zx7p: {kubelet ip-172-18-9-141.ec2.internal} Unhealthy: Readiness probe failed: sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
sh: mysql: command not found
```
The test is:
```
• Failure [108.543 seconds]
[Conformance][templates] templateinstance readiness test
/go/src/github.com/openshift/origin/test/extended/templates/templateinstance_readiness.go:196
  should report ready soon after all annotated objects are ready [It]
  /go/src/github.com/openshift/origin/test/extended/templates/templateinstance_readiness.go:145

  Expected error:
      <*errors.errorString | 0xc42152d440>: {
          s: "templateinstance unexpectedly reported failure",
      }
      templateinstance unexpectedly reported failure
  not to have occurred

  /go/src/github.com/openshift/origin/test/extended/templates/templateinstance_readiness.go:144
```
@mrunalp @alexlarsson PTAL

**Comment by cyphar** [comment]
I would guess this likely this happens because we don't use terminals by default (so trying to set the process group on the pty fails for obvious reasons).

**Comment by runcom** [comment]
> I would guess this likely this happens because we don't use terminals by default (so trying to set the process group on the pty fails for obvious reasons).

mmm this test works with Docker, is Docker behaving differently?

**Comment by mrunalp** [comment]
Can we compare the terminal setting in both the config.json files? Also, I think that the terminal should be set to true for this one if it isn't already.

**Comment by runcom** [comment]
> Can we compare the terminal setting in both the config.json files? Also, I think that the terminal should be set to true for this one if it isn't already.

we don't get container logs/configs in CI as the test suite itself delete them. Best is to reproduce on host.

**Comment by rhatdan** [comment]
Has this been fixed? Worked on?

**Comment by tyrone-grech** [comment]
We are also impacted by a similar issue when trying to exec commands in a running container inside a pod:
`exec failed: failed to set the terminal from the stdin: inappropriate ioctl for device`

The container is spawned from jenkins-kubernetes pipeline plugin. The nodes are running CRI-O on Kubernetes 1.7

**Comment by rhatdan** [comment]
@runcom @mrunalp Any update on this?

**Comment by umohnani8** [comment]
This was fixed  by setting tty to true for the exec commands in probes.
