### ISSUE TITLE
CRI-O should allow internal hostport handling to be disabled

### ISSUE THREAD

**Issue by dcbw** [kubernetes-sigs/cri-o#941]
Kube's CNI driver intentionally doesn't do anything hostport related, because upstream decided that was something plugins had to do themselves.  CNI also has the 'portmap' plugin which is specifically designed to handle the hostport stuff.

But CRIO implements hostports and gives plugins that already do hostports (like openshift-sdn) no way to disable that functionality.

CRIO should likely punt hostport handling to ocicni, and in turn ocicni would inspect the plugin's capabilties from the CNI config JSON, and if the plugin declared portmap capability, not call portmapping for that pod+network combo.

**Comment by mrunalp** [comment]
@dcbw Sounds good. Is this something that we can add right now?

**Comment by runcom** [comment]
Ping @dcbw

**Comment by rhatdan** [comment]
@dcbw @runcom @mrunalp Is this still something we want?  Have we done it?

**Comment by rhatdan** [comment]
No action in another year.  I guess this is not something we need..  Reopen if you disagree.
